"""Import workflow: Import the Bruker dataset into the project (step 1 of the step process).
Process (API_CONTRACT §8 / G2B-002/G2B-009): Read-only experimental parameter + link necessary
file to raw/<exp_id>/<data_id>/ (hard link -> symbolic link -> copy fallback; fid.com wait for
the backend to write the file entity copy) -> SHA-256 fingerprint ->
metadata/<exp_id>-<data_id>.json -> WorkflowRun(import) registration. Do not generate FID, do
not generate spectrum (step 2/3 is completed by convert_to_fid and process/reconstruct_nus
respectively)."""

from __future__ import annotations

import logging
import os
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from core.data.bruker_reader import read_dataset
from core.data.internal_data_model import Experiment
from core.project import ProjectManager, WorkflowRun
from core.project.manager import atomic_write_json, sha256_file
from ui_support.i18n import tr

logger = logging.getLogger(__name__)

METADATA_SCHEMA_VERSION = "1.0"
IMPORT_WORKFLOW_REF = "import"

# The authoritative Bruker parameter/data file for fingerprint calculation (counted as it exists
# WorkflowRun.inputs).
KEY_FILES = ("acqus", "acqu2s", "acqu3s", "ser", "fid", "nuslist")

# Files that the backend will rewrite in the raw directory (such as fid.com generated by bruker
# -AUTO / patch_fid_com) must be physically copied and cannot be linked -- hard link/Symbolic links
# will write the modifications back to the source data (G2B-009 compatibility clause "fid.com and
# other backends generate files that are always written physically and are not affected").
# Conversion will be touch/rewrite profYZ.dat, entity copy to protect source.
# 2026-09-22: a real data set caught the source directory being rewritten -- BMRB 53374 ships
# profY.dat (no Z); it fell through to a symlink and the conversion wrote through into the
# source data set, changing its fingerprint. Both spellings are copied now.
WRITABLE_RAW_NAMES = {"fid.com", "profY.dat", "profYZ.dat"}


class ImportWorkflowError(Exception):
    """Import workflow error (parameter check/IO/Project status)."""


class KineticsUnsupportedError(ImportWorkflowError):
    """Dynamics/The variable delay series is not within the current import capability range."""


@dataclass
class ImportResult:
    """A summary of the results of an import (GUI for display)."""

    experiment_id: str
    run_id: str
    source: Path
    raw_dir: Path | None
    metadata_path: Path
    checksums: dict[str, str]
    file_count: int
    total_bytes: int
    warnings: list[str] = field(default_factory=list)
    data_id: str = ""  # schema 1.2:Data entry d_001.


def _dataset_summary(experiment: Experiment) -> dict[str, Any]:
    """Compresses the Experiment into a serializable digest of metadata JSON."""
    return {
        "dataset_id": experiment.dataset_id,
        "ndim": experiment.ndim,
        "dimensions": [
            {
                "logical_axis": dim.logical_axis,
                "nucleus": dim.nucleus,
                "sf": dim.sf,
                "sw": dim.sw,
                "o1": dim.o1,
                "o1p": dim.o1p,
                "td": dim.td,
                "ft_size": dim.ft_size,
                "acquisition_mode": dim.acquisition_mode,
                "role": dim.role.value if dim.role else "",
            }
            for dim in experiment.dimensions
        ],
        "sampling": {
            "mode": experiment.sampling.mode.value,
            "sampling_fraction": experiment.sampling.sampling_fraction,
            "schedule_type": experiment.sampling.schedule_type,
        },
        "experiment_type": {
            "name": experiment.experiment_type.name,
            "confidence": experiment.experiment_type.confidence,
            "evidence": list(experiment.experiment_type.evidence),
        },
    }


def _iter_files(root: Path) -> list[Path]:
    """All files under directory (sorted by relative paths to ensure stable list)."""
    return sorted(p for p in root.rglob("*") if p.is_file())


def _manifest(root: Path) -> tuple[dict[str, str], int, int]:
    """Calculate SHA-256 for each file in directory and return (relative path -> summary, number of
    files, number of bytes)."""
    checksums: dict[str, str] = {}
    total_bytes = 0
    for path in _iter_files(root):
        rel = path.relative_to(root).as_posix()
        checksums[rel] = sha256_file(path)
        total_bytes += path.stat().st_size
    return checksums, len(checksums), total_bytes


def _key_checksums(root: Path) -> dict[str, str]:
    """Authoritative Bruker file fingerprint (ser/fid large files only count as existing ones)."""
    return {
        name: sha256_file(root / name)
        for name in KEY_FILES
        if (root / name).is_file()
    }


def _validate_dataset_dir(path: Path) -> None:
    if not (path / "acqus").is_file():
        raise ImportWorkflowError(tr(
            "Not a Bruker dataset directory (acqus is missing): "
            "{p0}",
            p0=path,
        ))


def _link_one(src: Path, dst: Path) -> str:
    """Link a single file: symbolic link -> hard link -> copy fallback (G2B-009, user-specified
    soft link takes precedence)."""
    try:
        os.symlink(src, dst)
        return "symlink"
    except OSError:
        pass
    try:
        os.link(src, dst)
        return "hardlink"
    except OSError:
        pass
    shutil.copy2(src, dst)
    return "copy"


def _link_tree(src: Path, dst: Path, stats: dict[str, int]) -> None:
    """Establish a link tree according to the source relative structure: directory mkdir, file link
    (G2B-009). The backend can write file (WRITABLE_RAW_NAMES, such as fid.com) entity copy, no
    link."""
    dst.mkdir(parents=True, exist_ok=True)
    for item in sorted(src.iterdir()):
        source_item = src / item.name
        dest_item = dst / item.name
        if source_item.is_dir():
            _link_tree(source_item, dest_item, stats)
        elif item.name in WRITABLE_RAW_NAMES:
            shutil.copy2(source_item, dest_item)
            stats["writable"] += 1
        else:
            stats[_link_one(source_item, dest_item)] += 1


def _raise_if_kinetics(experiment) -> None:
    """Dynamics/Variable delay series are prohibited from importing; Intercepts before creating
    entry and copying file."""
    from core.experiment.experiment_classifier import is_kinetics

    if is_kinetics(experiment):
        raise KineticsUnsupportedError(
            tr(
                "a kinetics experiment was detected (variable delay / time series); the current "
                "product does not support importing "
                "it",
            )
        )


def import_data(
    manager: ProjectManager,
    exp_id: str,
    source: Path | str,
    *,
    segments: list[Path | str] | None = None,
    copy: bool = True,
    segmented: bool = False,
) -> ImportResult:
    """Import data into the experiment: read-only parameter + link raw/<exp_id>/<data_id>/ +
    metadata + import run. G2B-009: raw read-only file default symbolic link (user requirement),
    Fallback hard link on failure/copy. does not generate FID, does not generate spectrum; the
    caller needs to manager.save() by itself."""
    if manager.project is None or manager.root is None:
        raise ImportWorkflowError(tr("Project is not loaded and data cannot be imported"))
    src = Path(source).resolve()
    segment_paths: list[Path] = []
    segment_kind: str | None = None
    segment_label: str | None = None
    if segmented:
        # Single data segment collection: source is the container directory containing all segments
        # (different from batch import, which creates entries for multiple independent data sets;
        # here they are merged into one DataEntry).
        from core.data.bruker_reader import (
            classify_segment_kind,
            read_dataset_container,
        )

        experiment, discovered = read_dataset_container(src)
        _raise_if_kinetics(experiment)
        if len(discovered) < 2:
            raise ImportWorkflowError(
                    tr(
                    "segmented import requires at least 2 segmented subdirectories containing "
                    "acqus (non-data subdirectories are ignored): "
                    "{p0}",
                    p0=src,
                )
            )
        experiment.dataset_id = src.name  # Container name as data identifier.
        segment_paths = [Path(seg).resolve() for seg in discovered]
        # 0.2.199-patch29cu: Identify repeated experiment superposition (uniform/NUS same point) and
        # NUS segmentation.
        segment_kind = classify_segment_kind(discovered)
        segment_label = {
            "repeat_uniform": tr("Repeat-experiment overlay (uniform, identical parameters)"),
            "repeat_nus": tr("Repeat-experiment overlay (NUS, identical sampling points)"),
            "segmented_nus": tr("segmented (NUS complementary sampling point)"),
        }.get(segment_kind, segment_kind)
        experiment.sampling.evidence.append(tr("Multi-segment type: {p0}", p0=segment_label))
    else:
        _validate_dataset_dir(src)
        experiment = read_dataset(src)
        _raise_if_kinetics(experiment)
        segment_paths = [Path(seg).resolve() for seg in (segments or [])]
        for seg in segment_paths:
            _validate_dataset_dir(seg)


    warnings: list[str] = []
    link_stats = {"hardlink": 0, "symlink": 0, "copy": 0, "writable": 0}
    should_copy = copy
    if should_copy and src.is_relative_to(manager.root):
        warnings.append(
            tr(
            "The source directory is already in the project, skip copying (refer to the original "
            "path): "
            "{p0}",
            p0=src,
        ))
        should_copy = False

    data_entry = manager.import_data(exp_id, str(src), segments=segment_paths)
    data_id = data_entry.id

    run: WorkflowRun | None = None
    copied_dir: Path | None = None
    metadata_path = manager.data_metadata_path(exp_id, data_id)
    try:
        effective_root = src
        if should_copy:
            copied_dir = manager.data_dir(exp_id, data_id, "raw")
            if segmented:
                # Single data segment collection: only copies each segment to raw/segments/NN, does
                # not copy container-level miscellaneous items (such as script); distinguished from
                # batch import (multiple DataEntry).
                seg_base = copied_dir / "segments"
                seg_base.mkdir(parents=True)
                copied_segments: list[str] = []
                for index, seg in enumerate(segment_paths, start=1):
                    dest = seg_base / f"{index:02d}"
                    _link_tree(seg, dest, link_stats)
                    copied_segments.append(str(dest))
                data_entry.segments = copied_segments
                data_entry.raw_dir = copied_dir.relative_to(manager.root).as_posix()
                effective_root = copied_dir
            else:
                _link_tree(src, copied_dir, link_stats)
                data_entry.raw_dir = copied_dir.relative_to(manager.root).as_posix()
                if segment_paths:
                    seg_base = copied_dir / "segments"
                    seg_base.mkdir()
                    copied_segments = []
                    for index, seg in enumerate(segment_paths, start=1):
                        dest = seg_base / f"{index:02d}"
                        _link_tree(seg, dest, link_stats)
                        copied_segments.append(str(dest))
                    data_entry.segments = copied_segments
                effective_root = copied_dir
            if link_stats["copy"]:
                warnings.append(
                    tr(
                        "{p0} file(s) could not be linked and were copied "
                        "instead",
                        p0=link_stats['copy'],
                    )
                )

        if segmented and segment_paths:
            checksums = {}
            for index, seg in enumerate(segment_paths, start=1):
                for name, digest in _key_checksums(seg).items():
                    checksums[f"seg_{index:02d}/{name}"] = digest
        else:
            checksums = _key_checksums(effective_root)
        manifest_checksums, file_count, total_bytes = _manifest(effective_root)
        data_entry.checksums = checksums

        inputs = {"source_path": str(src)}
        inputs.update(
            {f"sha256:{name}": digest for name, digest in sorted(checksums.items())}
        )
        run = manager.start_run(
            exp_id,
            workflow_ref=IMPORT_WORKFLOW_REF,
            inputs=inputs,
            params={
                "copy": should_copy,
                "link_stats": dict(link_stats),
                "data_id": data_id,
                "segments": [str(seg) for seg in data_entry.segments],
                "segment_kind": segment_kind,
                "file_count": file_count,
                "total_bytes": total_bytes,
            },
        )

        metadata = {
            "schema_version": METADATA_SCHEMA_VERSION,
            "experiment_id": exp_id,
            "data_id": data_id,
            "source_path": str(src),
            "copied_to": (
                copied_dir.relative_to(manager.root).as_posix()
                if copied_dir is not None
                else None
            ),
            "imported_at": data_entry.imported_at,
            "dataset": _dataset_summary(experiment),
            "segments": [str(seg) for seg in data_entry.segments],
            "segment_kind": segment_kind,
            "segment_kind_label": segment_label,
            "link_stats": dict(link_stats),  # G2B-009:hardlink/symlink/copy/writable
            "manifest": {
                "file_count": file_count,
                "total_bytes": total_bytes,
                "checksums": manifest_checksums,
            },
            "workflow_run_id": run.run_id,
        }
        atomic_write_json(metadata_path, metadata)
        data_entry.metadata_path = metadata_path.relative_to(manager.root).as_posix()

        outputs = {"metadata": metadata_path.relative_to(manager.root).as_posix()}
        if copied_dir is not None:
            outputs["raw_dir"] = copied_dir.relative_to(manager.root).as_posix()
        manager.finish_run(
            run.run_id,
            "success",
            outputs=outputs,
            message=tr("import completed")
            if segment_label is None
            else tr("import complete({p0})", p0=segment_label),
        )
    except Exception:
        if run is not None:
            try:
                manager.finish_run(
                    run.run_id, "failed", message=tr(
                        "Import failed, registration has been rolled "
                        "back",
                    )
                )
            except Exception:  # noqa: BLE001 - Rollback failure does not mask original error.
                pass
        if copied_dir is not None and copied_dir.is_dir():
            shutil.rmtree(copied_dir)
        if metadata_path.is_file():
            metadata_path.unlink()
        if manager.project is not None:
            entry = manager.project.experiment(exp_id)
            if entry is not None and data_entry in entry.data:
                entry.data.remove(data_entry)
        raise

    return ImportResult(
        experiment_id=exp_id,
        run_id=run.run_id,
        source=src,
        raw_dir=copied_dir,
        metadata_path=metadata_path,
        checksums=checksums,
        file_count=file_count,
        total_bytes=total_bytes,
        warnings=warnings,
        data_id=data_id,
    )


def import_bruker_dataset(
    manager: ProjectManager,
    source: Path | str,
    *,
    title: str = "",
    sample_id: str = "",
    segments: list[Path | str] | None = None,
    copy: bool = True,
) -> ImportResult:
    """Convenience entry (backwards compatible): Create an experiment and import the first data.
    Equivalent to create_experiment + import_data; remove blank experiments on failure."""
    if manager.project is None:
        raise ImportWorkflowError(tr("project is not loaded, cannot import experiment"))
    entry = manager.create_experiment(title=title, sample_id=sample_id)
    try:
        return import_data(manager, entry.id, source, segments=segments, copy=copy)
    except Exception:
        if (
            manager.project is not None
            and entry in manager.project.experiments
            and not entry.data
        ):
            manager.project.experiments.remove(entry)
        raise


def import_segmented_dataset(
    manager: ProjectManager,
    source: Path | str,
    *,
    title: str = "",
    sample_id: str = "",
    copy: bool = True,
    exp_id: str = "",
) -> ImportResult:
    """Single data segment collection and import: source is a container directory containing all
    segments, merged into one DataEntry. It is clearly distinguished from batch import: batch
    import creates entries for multiple independent data sets under the container; this entry
    treats each segment directly containing acqus under the container as the sampling segment of
    the same collection (read_segments verification Dimension/nuclear/TD/Spectral width
    consistent), merges it into one piece of data, and is converted segment by segment by the
    back end + addNMR merge. G2B-011: exp_id If it is not empty, it will be imported into the
    specified experiment type (verification exists), if it is empty, it will be created (current
    situation)."""
    if manager.project is None:
        raise ImportWorkflowError(tr("project is not loaded, cannot import experiment"))
    if exp_id:
        if manager.project.experiment(exp_id) is None:
            raise ImportWorkflowError(tr("experiment type does not exist: {p0}", p0=exp_id))
        return import_data(manager, exp_id, source, segmented=True, copy=copy)
    entry = manager.create_experiment(title=title, sample_id=sample_id)
    try:
        return import_data(manager, entry.id, source, segmented=True, copy=copy)
    except Exception:
        if (
            manager.project is not None
            and entry in manager.project.experiments
            and not entry.data
        ):
            manager.project.experiments.remove(entry)
        raise


__all__ = [
    "IMPORT_WORKFLOW_REF",
    "ImportResult",
    "ImportWorkflowError",
    "import_segmented_dataset",
    "import_bruker_dataset",
    "import_data",
]


def apply_user_experiment_type(
    manager: ProjectManager,
    exp_id: str,
    data_id: str,
    name: str,
) -> bool:
    """GUI Authoritatively writes back the experiment type selected by user
    metadata(0.2.199-patch29fd)."""
    if manager.project is None or manager.root is None:
        return False
    try:
        entry = manager.project.experiment(exp_id)
        if entry is None:
            return False
        path = manager.data_metadata_path(exp_id, data_id)
        data_entry = next((d for d in entry.data if d.id == data_id), None)
        if not path.is_file() and data_entry is not None and data_entry.metadata_path:
            mp = Path(data_entry.metadata_path)
            path = mp if mp.is_absolute() else manager.root / mp
        if not path.is_file():
            return False
        import json

        payload = json.loads(path.read_text(encoding="utf-8"))
        value = {
            "name": str(name),
            "confidence": 1.0,
            "evidence": ["gui_user_selected"],
        }
        dataset = dict(payload.get("dataset") or {})
        dataset["experiment_type"] = value
        payload["dataset"] = dataset
        payload["experiment_type"] = value
        atomic_write_json(path, payload)
        return True
    except Exception:
        logger.debug("Failed to persist user experiment type", exc_info=True)
        return False

