"""Memory phase search engine (unified solution, 2026-08-17). Move the old
optimize_phase_sequential axis-by-axis search/gate/joint review to the memory as it is: the
candidate spectrum is no longer generated by the backend, but frequency domain rotation is
performed on the first-pass replication preview data to obtain the real part, and then the same
set of "fixed trace median net absorption" scoring judgment is used. - Score: 50 x (locked trace
+/-5 window net absorption median + 1), same as the old scheme; - Search: Coarse grid p0 0-330°
step 30° (p1=0) -> 1/3 Decrease refinement to 5° (p1 fixed) -> Platform circle median p0 sub-
degree refinement -> +/-90° symmetry disambiguation -> End p1 {0,+/-22.5}; - gate: scoring
margin <0.05 -> Reproducibility (odd and even subsampling) -> three-level fallback; - joint
review: p1 +/-5° combination of each axis + all zeros, fixed trace score for each axis and
averaged."""

from __future__ import annotations

import math
import time
from collections.abc import Callable
from dataclasses import dataclass, field

import numpy as np

from ui_support.i18n import tr

# Phase scoring constants and grid helper functions (0.2.164 migrated from workflow.phase_optimize;
# the old brute-force optimisation module has been removed, memory search is the only
# implementation).
PHASE_SCORE_FLAT_MARGIN = 0.05
PHASE_REPRODUCIBILITY_TOL = 10.0
PHASE_PLATEAU_TOL = 1.0
PHASE_SYMMETRY_TOL = 2.5

# 0.2.199-patch29fs(user): Arbitration is only done for axes that are "mixed and have a low net
# score" -- good spectra (net score >= 95) are equally correct without arbitration, Also eliminates
# the need to rotate the entire batch of rows/paired optimisation time; pair tail differences of low
# net score axes (such as 99.8 vs 99.9) no longer have the chance to turn the good axis by mistake
# (VM sampleB axis 1 0 -> 5 chain with bias r2 lesson).
PAIR_ARBITER_NET_GATE = 95.0


def _axis_traces(real: np.ndarray, axis: int) -> np.ndarray:
    """Expand the spectrum along the axis into (n_trace, axis_len), which is applicable to any
    dimension."""
    moved = np.moveaxis(np.asarray(real, dtype=float), axis, -1)
    return moved.reshape(-1, moved.shape[-1])


def _trace_indices_fixed(
    real: np.ndarray, axis: int, threshold: float = 0.0
) -> tuple[list[int], list[int]]:
    """Return the signal trace index and strongest point position along axis (patch29ff
    vectorization, consistent results)."""
    traces = _axis_traces(real, axis)
    mag = np.abs(traces)
    peaks = np.argmax(mag, axis=-1)
    maxima = mag[np.arange(traces.shape[0]), peaks]
    keep = maxima > threshold
    idx = np.nonzero(keep)[0]
    return [int(i) for i in idx], [int(peaks[i]) for i in idx]


def _grid_step(values: tuple[float, ...]) -> float:
    """The step size of the equidistant grid (the median of adjacent differences); less than 2
    points returns 0."""
    if len(values) < 2:
        return 0.0
    diffs = sorted(
        float(values[i + 1]) - float(values[i]) for i in range(len(values) - 1)
    )
    return float(diffs[len(diffs) // 2])


def _refine_steps(coarse_step: float, final_step: float) -> list[float]:
    """A sequence of refinements from coarse step size to target step size (approximately 1/3
    decreasing, with the last level being the target step size)."""
    steps: list[float] = []
    s = float(coarse_step)
    while True:
        nxt = s / 3.0
        if nxt <= final_step:
            steps.append(float(final_step))
            break
        steps.append(nxt)
        s = nxt
    return steps


def _refine_window(center: float, prev_step: float, new_step: float) -> list[float]:
    """Refinement window around centre: Cover +/-prev_step/2, press new_step to pick the point."""
    half = prev_step / 2.0
    n = int(math.ceil(half / new_step))
    return [center + k * new_step for k in range(-n, n + 1)]


def rotate_real(
    complex_arr: np.ndarray, axis: int, p0: float, p1: float
) -> np.ndarray:
    """Memory frequency domain rotation takes the real part, the same convention as nmrPipe PS:
    phase(k) = p0 + p1·k/(n-1), point-by-point complex multiplication exp(i·phase), takes the
    real part (= -di semantics)."""
    arr = np.asarray(complex_arr, dtype=np.complex128)
    # 0.2.199-patch29dp: When p1=0, phase has nothing to do with k, scalar rotation (avoiding the
    # point-by-point complex multiplication of the entire axis ramp array -- 3D NUS The main
    # overhead of large array ~50 times of candidate scoring).
    if abs(p1) < 1e-9:
        c = float(np.cos(np.deg2rad(p0)))
        s = float(np.sin(np.deg2rad(p0)))
        return arr.real * c - arr.imag * s
    n = arr.shape[axis]
    k = np.arange(n, dtype=float)
    ramp = np.exp(1j * np.deg2rad(p0 + p1 * k / max(n - 1, 1)))
    shape = [1] * arr.ndim
    shape[axis] = n
    return np.real(arr * ramp.reshape(shape))


def _gather_slices(
    rows: np.ndarray, starts: np.ndarray, ends: np.ndarray
) -> tuple[np.ndarray, np.ndarray]:
    """Each row [start,end) slices are collected into an equal-width matrix (patch29ff, out-of-
    bounds NaN mask)."""
    n_rows, width = rows.shape
    maxlen = int(np.max(ends - starts)) if n_rows else 0
    if maxlen <= 0:
        return np.zeros((n_rows, 0)), np.zeros((n_rows, 0), dtype=bool)
    cols = np.arange(maxlen)[None, :]
    offs = starts[:, None] + cols
    valid = (offs < ends[:, None]) & (offs < width)
    idx = np.where(valid, offs, 0)
    return rows[np.arange(n_rows)[:, None], idx], valid


def _median_rows(gathered: np.ndarray, valid: np.ndarray) -> np.ndarray:
    """Median number of valid values by row (equivalent to np.median row by row, the last digit
    is allowed to be 1e-16)."""
    counts = valid.sum(axis=1)
    if counts.size == 0:
        return np.zeros(0)
    s = np.sort(np.where(valid, gathered, np.inf), axis=1)
    k1 = (counts - 1) // 2
    k2 = counts // 2
    vals = np.take_along_axis(s, np.stack([k1, k2], axis=1), axis=1)
    return 0.5 * (vals[:, 0] + vals[:, 1])


def _window_nets(
    real: np.ndarray,
    axis: int,
    indices: list[int],
    positions: list[int],
    *,
    half_width: int | None = None,
) -> list[float]:
    """The net absorption of each window signature (pos+neg)/total (same formula as the old
    _window_metric). The positive and negative judgments are made by first leveling the baseline
    -- taking the mean median value of the baseline area on both sides of the peak (+/-6..18
    points) as the baseline level, and then subtracting the baseline from the window to divide
    it into positive and negative; the overall offset of the baseline (positive or negative) no
    longer contaminates the net absorption (0.2.175 user plan). half_width(points) Adjustable
    window half-width (0.2.199-patch29dn, Plan B test): Default 5 is consistent with the old
    behaviour; normalisation by line width/resolution (high resolution window is larger) can
    eliminate "+/-5 points covering too large line width at low resolution, resulting in phase
    optimal offset" (sampleI F1 at 431 points preview 105°, 1024 points final spectrum optimal
    90°)."""
    hw = 5 if half_width is None else max(int(half_width), 1)
    moved = np.moveaxis(real, axis, -1)
    traces = moved.reshape(-1, moved.shape[-1])
    nets: list[float] = []
    for index, peak in zip(indices, positions):
        if index < 0 or index >= traces.shape[0]:
            continue
        n = traces.shape[1]
        left_base = traces[index, max(0, peak - 3 * hw - 3) : max(0, peak - hw - 1)]
        right_base = traces[
            index, min(n, peak + hw + 2) : min(n, peak + 3 * hw + 4)
        ]
        if left_base.size >= 4 and right_base.size >= 4:
            baseline = 0.5 * (
                float(np.median(left_base)) + float(np.median(right_base))
            )
        else:
            baseline = float(np.median(traces[index]))
        profile = traces[index, max(0, peak - hw) : peak + hw + 1]
        peak_h = float(np.max(np.abs(profile)))
        # Baseline is flattened only when the relative peak height shift is significant (>= 1%);
        # baseline is flattened and the spectrum remains zero-bounded.
        if peak_h > 1e-12 and abs(baseline) / peak_h >= 0.01:
            profile = profile - baseline
        positive = float(np.clip(profile, 0.0, None).sum())
        negative = float(np.clip(profile, None, 0.0).sum())
        total = float(np.abs(profile).sum())
        nets.append((positive + negative) / total if total else 0.0)
    return nets


def _window_nets_from_rows(
    rows: np.ndarray,
    positions: list[int],
    *,
    half_width: int | None = None,
) -> list[float]:
    """Lock the net absorption of each trace line (patch29ff vectorization, equivalent rewriting;
    baseline translation only acts on valid points within the peak window, out-of-boundary zero
    filling does not participate in translation)."""
    hw = 5 if half_width is None else max(int(half_width), 1)
    n_rows = rows.shape[0]
    if n_rows == 0:
        return []
    width = rows.shape[1]
    peaks = np.asarray(positions, dtype=int)
    ls = np.maximum(0, peaks - 3 * hw - 3)
    le = np.maximum(0, peaks - hw - 1)
    lmat, lvalid = _gather_slices(rows, ls, le)
    rs = np.minimum(width, peaks + hw + 2)
    re = np.minimum(width, peaks + 3 * hw + 4)
    rmat, rvalid = _gather_slices(rows, rs, re)
    lcount = lvalid.sum(axis=1)
    rcount = rvalid.sum(axis=1)
    ok = (lcount >= 4) & (rcount >= 4)
    lmed = np.zeros(n_rows)
    rmed = np.zeros(n_rows)
    if ok.any():
        lmed[ok] = _median_rows(lmat[ok], lvalid[ok])
        rmed[ok] = _median_rows(rmat[ok], rvalid[ok])
    baseline = np.where(ok, 0.5 * (lmed + rmed), np.median(rows, axis=1))
    ps = np.maximum(0, peaks - hw)
    pe = peaks + hw + 1
    pmat, pvalid = _gather_slices(rows, ps, pe)
    profile = np.where(pvalid, pmat, 0.0)
    peak_h = np.max(np.abs(profile), axis=1)
    cond = (
        (peak_h > 1e-12)
        & (np.abs(baseline) / np.maximum(peak_h, 1e-30) >= 0.01)
    )
    shifted = np.where(pvalid, pmat - baseline[:, None], 0.0)
    profile = np.where(cond[:, None], shifted, profile)
    positive = np.clip(profile, 0.0, None).sum(axis=1)
    negative = np.clip(profile, None, 0.0).sum(axis=1)
    total = np.abs(profile).sum(axis=1)
    nets = np.where(total > 0, (positive + negative) / total, 0.0)
    return [float(v) for v in nets]


def score_locked_memory(
    rows: np.ndarray,
    positions: list[int],
    p0: float,
    p1: float,
    *,
    sign_mode: str = "uniform",
    net_half_width: int | None = None,
) -> float:
    """Lock trace row scoring (0.2.199-patch29dp): only rotate the locked row, no longer perform a
    duplicate rotation on the entire array for each candidate (3D NUS (256,256,586) Each axis
    search 23-25s -> sub-second level)."""
    real = rotate_real(rows, -1, p0, p1)
    nets = _window_nets_from_rows(
        real, positions, half_width=net_half_width
    )
    if not nets:
        return 50.0
    if sign_mode == "mixed":
        score = 50.0 * (float(np.median(np.abs(nets))) + 1.0)
        strong = [nn for nn in nets if abs(nn) > 0.35]
        if strong:
            pos = sum(1 for nn in strong if nn > 0)
            neg = sum(1 for nn in strong if nn < 0)
            if pos >= 1 and neg >= 1:
                return score
            return score * 0.7
        return score
    return 50.0 * (float(np.median(nets)) + 1.0)


def score_axis_memory(
    complex_arr: np.ndarray,
    axis: int,
    p0: float,
    p1: float,
    indices: list[int],
    positions: list[int],
    *,
    sign_mode: str = "uniform",
    net_half_width: int | None = None,
) -> float:
    """Candidate phase score (0-100). sign_mode="mixed" (HNCACB and other positive and negative
    peaks coexist): Absorption = the median of |net absorption of each window| -- Zhengfeng/Even
    negative peaks can get high scores; then require the coexistence of positive and negative
    strong and weak peaks (missing a symbol penalty (Positive peak preference resolves +/-180
    ambiguities)."""
    real = rotate_real(complex_arr, axis, p0, p1)
    nets = _window_nets(
        real, axis, indices, positions, half_width=net_half_width
    )
    if not nets:
        return 50.0
    if sign_mode == "mixed":
        score = 50.0 * (float(np.median(np.abs(nets))) + 1.0)
        strong = [n for n in nets if abs(n) > 0.35]
        if strong:
            pos = sum(1 for n in strong if n > 0)
            neg = sum(1 for n in strong if n < 0)
            if pos >= 1 and neg >= 1:
                return score
            return score * 0.7
        return score
    median = float(np.median(nets))
    return 50.0 * (median + 1.0)


def _lock_discrete_traces(
    complex_arr: np.ndarray,
    axis: int,
    *,
    prominence_min: float = 2.5,
    window: int = 10,
    max_duty: float = 0.5,
    threshold_pct: float = 95.0,
    discrete: bool = True,
) -> tuple[list[int], list[int]]:
    """Lock the "discrete peak" trace for phase modulation scoring. It is consistent with manual
    nmrDraw's "pick discrete peak phase modulation": the discrete peak selection (discrete=True)
    threshold is set to the low quantile (default 95, the central large group will be raised
    99.5 quantile to eliminate discrete peaks), and then the peak shape sharpness is used to
    filter --- peak position +/-window >= the proportion of the half-high point (duty) <=
    max_duty And the peak top is significant (prominence) relative to the low quantile of the
    local background. The central mixed peak cluster (dense peak cluster) occupies a large
    proportion of the window and is excluded; when there are no discrete peaks, the threshold is
    gradually lowered, and finally all traces are rolled back. This option is only used for
    mixed (HNCACB and other positive and negative coexistence) experiments --- Uniform spectrum
    can use the old lock (99.5 quantile of all strong traces), discrete filtering will change
    the trace set to d103 and other band biases 180° (VM d103 regression calibration)."""
    real0 = np.real(complex_arr)
    if not discrete:
        noise_old = float(np.std(real0[:80, :40])) if real0.size else 0.0
        thr_old = max(float(np.percentile(real0, 99.5)), noise_old * 5.0)
        out = _trace_indices_fixed(real0, axis, thr_old)
        if out[0]:
            return out
        return _trace_indices_fixed(real0, axis, -1.0)
    moved = np.moveaxis(real0, axis, -1)
    traces = moved.reshape(-1, moved.shape[-1])
    n = moved.shape[-1]
    noise = float(np.std(real0[:80, :40])) if real0.size else 0.0
    for pct in (threshold_pct, 75.0):
        threshold = max(float(np.percentile(real0, pct)), noise * 5.0)
        indices: list[int] = []
        positions: list[int] = []
        for i in range(traces.shape[0]):
            mag = np.abs(traces[i])
            peak = int(np.argmax(mag))
            if float(mag[peak]) <= threshold:
                continue
            half = 0.5 * float(mag[peak])
            lo = max(0, peak - window)
            hi = min(n, peak + window + 1)
            seg = mag[lo:hi]
            if seg.size == 0:
                continue
            duty = float(np.mean(seg >= half))
            if duty > max_duty:
                continue
            bg = float(np.percentile(seg, 25.0))
            if float(mag[peak]) / (bg + 1e-12) >= prominence_min:
                indices.append(i)
                positions.append(peak)
        if indices:
            return indices, positions
    return _trace_indices_fixed(real0, axis, -1.0)


def _subsampled_score_memory(
    real: np.ndarray, axis: int, k: int = 500, group: str = "even"
) -> float:
    """Take a half-group subsampling of top-K strong traces with peak height along axis, and
    evaluate in-memory phase_quality (same index as the old scheme _subsampled_score, except
    that the input is a memory array)."""
    from core.qc import phase_quality

    moved = np.moveaxis(real, axis, -1)
    traces = moved.reshape(-1, moved.shape[-1])
    peak_mag = np.max(np.abs(traces), axis=-1)
    order = np.argsort(peak_mag)[::-1][:k]
    selected = order[0::2] if group == "even" else order[1::2]
    if selected.size == 0:
        return 0.0
    return float(phase_quality.evaluate(traces[selected]).score)


def _subsampled_score_rows(
    rows: np.ndarray, k: int = 500, group: str = "even"
) -> float:
    """Locks the top-K half-set of subsampled scores for trace rows (0.2.199-patch29dp, row
    variant)."""
    from core.qc import phase_quality

    peak_mag = np.max(np.abs(rows), axis=-1)
    order = np.argsort(peak_mag)[::-1][:k]
    selected = order[0::2] if group == "even" else order[1::2]
    if selected.size == 0:
        return 0.0
    return float(phase_quality.evaluate(rows[selected]).score)


def _symmetry_memory(real: np.ndarray, axis: int) -> float:
    """+/-90° symmetry index for disambiguation (same as the old scheme
    phase_quality.profile_symmetry_axis)."""
    from core.qc import phase_quality

    return float(phase_quality.profile_symmetry_axis(real, axis))


@dataclass
class MemoryAxisResult:
    """In-memory phase search results for a dimension."""

    axis: int
    phase: tuple[float, float]
    score: float
    coarse_best: tuple[float, float]
    coarse_margin: float
    flat: bool
    traces: tuple[list[int], list[int]] = field(default_factory=lambda: ([], []))
    score_map: dict[tuple[float, float], float] = field(default_factory=dict)
    logs: list[str] = field(default_factory=list)


def _opposite_pair_profiles(
    real_rows: np.ndarray, positions: list[int],
    *, window: int = 20, radius: int = 6,
) -> list[np.ndarray]:
    """Extract the "adjacent positive and negative peak pairs" profile on the locked trace."""
    n = int(real_rows.shape[1])
    out: list[np.ndarray] = []
    for row, peak in zip(real_rows, positions):
        peak = int(peak)
        if not (0 <= peak < n):
            continue
        main = float(row[peak])
        if abs(main) < 1e-12:
            continue
        lo = max(0, peak - window)
        hi = min(n, peak + window + 1)
        seg = row[lo:hi]
        opp = np.where(np.sign(seg) * np.sign(main) < 0, seg, 0.0)
        idx = int(np.argmax(np.abs(opp)))
        if opp[idx] == 0.0:
            continue
        other = lo + idx
        a, b = min(peak, other), max(peak, other)
        if b - a < 2:
            continue
        p0 = max(0, a - radius)
        p1 = min(n, b + radius + 1)
        prof = row[p0:p1].astype(float)
        if prof.size < 5 or float(np.std(prof)) < 1e-12:
            continue
        out.append(prof)
    return out


def _pair_similarity(real_rows: np.ndarray, positions: list[int]) -> float | None:
    """Median pairwise correlation of pairs of positive and negative peak profiles; log < 3 returns
    None."""
    profiles = _opposite_pair_profiles(real_rows, positions)
    if len(profiles) < 3:
        return None
    # 0.2.199-patch29fo - Modification: The large spectrum profile can be tens of thousands, and the
    # pairwise O(N^2) memory explosion (sampleJ 7.6 ten thousand pairs -> 43GB); pairwise
    # correlation after deterministic uniform sampling 0.2.199-patch29fq: upper limit 256 -> 4096 --
    # VM sampleB axis 0 measured 256, the pair scores of 30/90 are ≈ 100 (the discrimination is
    # smoothed, maintained 30°);4096 restores 30 -> 99.56/90 -> 100.0 (consistent with the full
    # profile 99.46/100.0, the pairwise matrix 4096² x 8B≈134MB is still safe).
    max_profiles = 4096
    if len(profiles) > max_profiles:
        idx = np.linspace(0, len(profiles) - 1, max_profiles).astype(int)
        profiles = [profiles[int(i)] for i in idx]
    fixed: list[np.ndarray] = []
    length = 32
    xi = np.linspace(0.0, 1.0, length)
    for prof in profiles:
        x = np.linspace(0.0, 1.0, prof.size)
        p = np.interp(xi, x, prof)
        p = p - float(np.mean(p))
        norm = float(np.linalg.norm(p))
        if norm < 1e-12:
            continue
        fixed.append(p / norm)
    if len(fixed) < 3:
        return None
    arr = np.asarray(fixed)
    dots = arr @ arr.T
    tri = dots[np.triu_indices(len(fixed), 1)]
    return float(np.median(tri))


def _pair_arbiter_score(real_rows: np.ndarray, positions: list[int]) -> float:
    """0-100: The lower the similarity, the better (the real mixed positive and negative peaks are
    different); No right/Insufficient logarithm=50."""
    sim = _pair_similarity(real_rows, positions)
    if sim is None:
        return 50.0
    return float(100.0 * (1.0 - max(0.0, min(1.0, sim))))


def search_axis_memory(
    complex_arr: np.ndarray,
    axis: int,
    *,
    p0_values: tuple[float, ...] = tuple(float(v) for v in range(0, 360, 30)),
    final_step: float = 5.0,
    refine: bool = True,
    sign_mode: str = "uniform",
    discrete: bool | None = None,
    net_half_width: int | None = None,
    cancel: Callable[[], bool] | None = None,
) -> MemoryAxisResult | None:
    """Perform in-memory phase search on the specified axis of the replica data (old algorithm
    judgment criteria, zero backend)."""
    _t_search0 = time.monotonic()
    arr = np.asarray(complex_arr, dtype=np.complex128)
    n = arr.shape[axis]
    if arr.ndim < 2 or n < 8:
        return None
    logs: list[str] = []
    scored: dict[tuple[float, float], float] = {}

    def _score(p0: float, p1: float) -> float:
        return score_locked_memory(
            locked_rows, trace_positions, p0, p1,
            sign_mode=sign_mode, net_half_width=net_half_width,
        )

    # Baseline (0,0) lock trace: mixed (HNCACB, etc.) use discrete peak selection to filter the
    # central mixed peak cluster (VM sampleB calibration: large clusters will be biased by phase,
    # discrete peaks are adjusted to F2=90°/F1≈0°); uniform is locked with the old (discrete
    # filtering will change the trace set, VM d103 was biased by 180°).
    use_discrete = (sign_mode == "mixed") if discrete is None else discrete
    trace_indices, trace_positions = _lock_discrete_traces(
        arr, axis, discrete=use_discrete
    )
    if not trace_indices:
        trace_indices, trace_positions = _trace_indices_fixed(
            np.real(arr), axis, -1.0
        )
    if not trace_indices:
        return None
    # 0.2.199-patch29dp: Extract only locked trace lines; candidate scoring rotates only these
    # lines.
    _moved = np.moveaxis(arr, axis, -1)
    _flat = _moved.reshape(-1, _moved.shape[-1])
    locked_rows = _flat[trace_indices]
    _t_lock_done = time.monotonic()

    def _run_batch(phases: list[tuple[float, float]]) -> None:
        for raw in phases:
            if cancel is not None and cancel():
                raise RuntimeError(tr("Task cancelled: Memory phase search terminated by user"))
            phase = (float(raw[0]) % 360.0, float(raw[1]))
            if phase in scored:
                continue
            scored[phase] = _score(phase[0], phase[1])

    _run_batch([(0.0, 0.0)])
    p0_step = _grid_step(tuple(p0_values))
    coarse = [(float(p0), 0.0) for p0 in p0_values]
    _run_batch(coarse)
    if not scored:
        return None
    coarse_done = [p for p in coarse if p in scored]
    coarse_sorted = sorted(coarse_done, key=lambda p: -scored[p])
    coarse_best = coarse_sorted[0]
    coarse_best_score = scored[coarse_best]
    p0_rivals = [
        s
        for p, s in scored.items()
        if p in coarse_done
        and abs((p[0] - coarse_best[0] + 180.0) % 360.0 - 180.0) > 1e-6
    ]
    coarse_margin = coarse_best_score - max(p0_rivals) if p0_rivals else 0.0
    steps0 = (
        _refine_steps(p0_step, final_step) if refine and p0_step > 0 else []
    )
    levels = len(steps0)
    if levels:
        prev0 = p0_step
        for level in range(levels):
            s0 = steps0[level]
            best = max(scored, key=lambda p: scored[p])
            w0 = _refine_window(best[0], prev0, s0)
            _run_batch([(p0, 0.0) for p0 in w0])
            prev0 = s0
    best_phase = max(scored, key=lambda p: scored[p])
    best_score = scored[best_phase]
    neighbor_scores = [
        s
        for p, s in scored.items()
        if p != best_phase and abs(p[1] - best_phase[1]) <= final_step
    ]
    flat = False
    if neighbor_scores:
        margin = best_score - max(neighbor_scores)
        if margin < PHASE_SCORE_FLAT_MARGIN:
            flat = True
            logs.append(
                tr(
                    "axis{p0}: phase scoring margin {p1:.2f} points(<{p2:g}), the scoring surface "
                    "is flat",
                    p0=axis,
                    p1=margin,
                    p2=PHASE_SCORE_FLAT_MARGIN,
                )
            )
        else:
            logs.append(
                tr(
                "axis{p0}: phase scoring margin {p1:.2f} points, the optimal is "
                "clearer",
                p0=axis,
                p1=margin,
            ))
    if not flat:
        neighbor_phases = [
            p for p in scored if abs(p[1] - best_phase[1]) <= final_step
        ]
        if len(neighbor_phases) >= 2:
            p1s: list[float] = []
            for group in ("even", "odd"):
                best_group: tuple[float, float] | None = None
                best_s = -1.0
                for p in neighbor_phases:
                    real = rotate_real(locked_rows, -1, p[0], p[1])
                    s = _subsampled_score_rows(real, group=group)
                    if s > best_s:
                        best_s, best_group = s, p
                p1s.append(float(best_group[1]) if best_group is not None else 0.0)
            if abs(p1s[0] - p1s[1]) > PHASE_REPRODUCIBILITY_TOL:
                flat = True
                logs.append(
                    tr(
                        "axis{p0}: Reproducibility check failed (top-K subsampling optimal p1 "
                        "{p1:g}/{p2:g}, difference>{p3:g}°),falling back to "
                        "(0,0)",
                        p0=axis,
                        p1=p1s[0],
                        p2=p1s[1],
                        p3=PHASE_REPRODUCIBILITY_TOL,
                    )
                )
    if flat:
        # 0.2.199-patch29fo(user): Add new scoring requirements for flatness -- pairwise positive
        # and negative peak similarity. phase staggered dispersion assigns systematic positive and
        # negative pairs (similar morphology) to each peak, and the real mixed spectrum positive and
        # negative peaks (Cα/Cβ, etc.) are different from each other. candidate = p1=0 and the net
        # separation is optimal <= +/-90 Disambiguation tolerance of scored candidate + zero phase
        # (No truncation); when the logarithm is enough, use it to re-evaluate the best and directly
        # finalize the decision.
        pair_tol = PHASE_SYMMETRY_TOL
        candidates = sorted(
            (
                p
                for p, s in scored.items()
                if s >= best_score - pair_tol and abs(p[1]) < 1e-9
            ),
            key=lambda p: -scored[p],
        )
        if (0.0, 0.0) in scored and (0.0, 0.0) not in candidates:
            candidates.append((0.0, 0.0))
        arb_ok = (
            sign_mode == "mixed"
            and best_score < PAIR_ARBITER_NET_GATE
            and len(candidates) >= 2
        )
        # 0.2.199-patch29fs(user): Good spectra do not arbitrate -- only axes that are mixed and
        # have a net score difference (<95) are made to arbitrate for positive and negative peaks;
        # the rest (including uniform) use coarse grid optimisation.
        if arb_ok:
            pair_scores: list[tuple[float, tuple[float, float]]] = []
            for cand in candidates:
                real_rows = rotate_real(locked_rows, -1, cand[0], cand[1])
                pair_scores.append(
                    (_pair_arbiter_score(real_rows, trace_positions), cand)
                )
            # Patch29fo-Repair 2: Round the pair scores to 0.01 first and then compare them. If the
            # scores are the same, the net score will be used -- For large spectrum pairs, the total
            # is often close to 100. The floating point tail difference will make 355° accidentally
            # exceed 0°.
            best_pair, pair_best_cand = max(
                pair_scores,
                key=lambda item: (round(item[0], 1), scored[item[1]]),
            )
            if pair_best_cand != best_phase:
                logs.append(
                    tr(
                        "axis{p0}: Main score is flat, pairwise positive and negative peak "
                        "similarity arbitration {p1}(net={p2:.2f}) → {p3}(net={p4:.2f}, "
                        "pair={p5:.2f}); "
                        "candidate=",
                        p0=axis,
                        p1=best_phase,
                        p2=scored[best_phase],
                        p3=pair_best_cand,
                        p4=scored[pair_best_cand],
                        p5=best_pair,
                    )
                    + ", ".join(
                        f"{c}=({scored[c]:.1f}/{q:.1f})" for q, c in pair_scores
                    )
                )
                best_phase = pair_best_cand
                best_score = scored[pair_best_cand]
            else:
                logs.append(
                    tr(
                        "axis{p0}: The main score is flat, and the similarity arbitration of "
                        "paired positive and negative peaks is maintained. "
                        "{p1}(pair={p2:.2f})",
                        p0=axis,
                        p1=best_phase,
                        p2=best_pair,
                    )
                )
        else:
            # Good score/No mixed/ candidate insufficient: retain the original flat bottom
            # (including zero phase fallback).
            zero_score = scored.get((0.0, 0.0))
            if coarse_best == (0.0, 0.0) and zero_score is not None:
                best_phase = (0.0, 0.0)
                best_score = zero_score
                logs.append(tr("axis{p0}: Fallback (0,0) (coarse mesh is optimally zero)", p0=axis))
            else:
                best_phase = coarse_best
                best_score = scored[coarse_best]
                logs.append(
                    tr(
                        "axis{p0}: The fine grid score is flat, and the coarse grid is optimal. "
                        "{p1} (coarse margin={p2:.2f} "
                        "point)",
                        p0=axis,
                        p1=coarse_best,
                        p2=coarse_margin,
                    )
                )
    if refine and not flat:
        # Platform circle median p0 (sub-degree refinement, default scoring path of the old scheme)
        # 0.2.199-patch29dn: The flat surface does not fall back -- The median of the flat area will
        # drift (for example, the coarse grid optimal 90° of sampleI F1 is changed to 80°),
        # maintaining the coarse grid optimal.
        plateau_p0 = [
            p[0] for p, s in scored.items() if s >= best_score - PHASE_PLATEAU_TOL
        ]
        if len(plateau_p0) >= 2:
            angles = np.deg2rad(plateau_p0)
            center = float(
                np.rad2deg(
                    np.arctan2(np.mean(np.sin(angles)), np.mean(np.cos(angles)))
                )
            )
            center = center % 360.0
            refined = (center, best_phase[1])
            if (
                abs((center - best_phase[0] + 180.0) % 360.0 - 180.0) > 0.5
                and refined not in scored
            ):
                _run_batch([refined])
            if refined in scored:
                r_score = scored[refined]
                if r_score >= best_score - PHASE_PLATEAU_TOL:
                    best_phase, best_score = refined, r_score
                    logs.append(
                        tr(
                            "axis{p0}: Platform circle median p0 -> {p1:.2f}° "
                            "(score={p2:.2f})",
                            p0=axis,
                            p1=center,
                            p2=r_score,
                        )
                    )
        # +/-90° symmetry disambiguation (old scheme NMRFlow;0.2.199-patch29dp with locked rows).
        best_real = rotate_real(locked_rows, -1, best_phase[0], best_phase[1])
        best_sym = _symmetry_memory(best_real, -1)
        for offset in (90.0, -90.0):
            cand = (best_phase[0] + offset, best_phase[1])
            if cand not in scored:
                _run_batch([cand])
            if cand in scored:
                c_score = scored[cand]
                if c_score >= best_score - PHASE_SYMMETRY_TOL:
                    c_sym = _symmetry_memory(
                        rotate_real(locked_rows, -1, cand[0], cand[1]), -1
                    )
                    if c_sym > best_sym + 0.05:
                        logs.append(
                            tr(
                                "axis{p0}: +/-90° symmetry disambiguation {p1} → {p2} (sym "
                                "{p3:.2f}→{p4:.2f})",
                                p0=axis,
                                p1=best_phase,
                                p2=cand,
                                p3=best_sym,
                                p4=c_sym,
                            )
                        )
                        best_phase, best_score = cand, c_score
                        best_sym = c_sym
        # P1 refinement {0, +/-22.5} (saturated 100 points short circuit).
        p1_refine_candidates = [0.0, 22.5, -22.5]
        if best_score >= 100.0 - 1e-9:
            p1_refine_candidates = []
            logs.append(tr("axis{p0}: Score saturated (100 points), skip p1 refinement", p0=axis))
        for p1 in p1_refine_candidates:
            cand = (best_phase[0] % 360.0, p1)
            if cand not in scored:
                _run_batch([cand])
            if cand in scored:
                c_score = scored[cand]
                if c_score > best_score:
                    logs.append(
                        tr(
                            "axis{p0}: p1 refinement {p1:g}° → {p2:g}° "
                            "(score={p3:.2f})",
                            p0=axis,
                            p1=best_phase[1],
                            p2=p1,
                            p3=c_score,
                        )
                    )
                    best_phase, best_score = cand, c_score
    # 0.2.199-patch29fe: Internal stage timing (does not change the algorithm, for hotspot
    # analysis).
    _wall = time.monotonic() - _t_search0
    logs.append(
        tr(
            "Internal memory search: locked trace takes time {p0:.2f}s,scoring / the rest takes "
            "{p1:.2f}s, {p2} candidates scored in {p3:.2f}s in "
            "total",
            p0=_t_lock_done - _t_search0,
            p1=_wall - (_t_lock_done - _t_search0),
            p2=len(scored),
            p3=_wall,
        )
    )
    return MemoryAxisResult(
        axis=axis,
        phase=(float(best_phase[0]), float(best_phase[1])),
        score=float(best_score),
        coarse_best=(float(coarse_best[0]), float(coarse_best[1])),
        coarse_margin=float(coarse_margin),
        flat=flat,
        traces=(list(trace_indices), list(trace_positions)),
        score_map=dict(scored),
        logs=logs,
    )


def joint_recheck_memory(
    axis_arrays: dict[str, np.ndarray],
    axis_index: dict[str, int],
    axis_traces: dict[str, tuple[list[int], list[int]]],
    fixed: dict[str, tuple[float, float]],
    *,
    final_step: float = 5.0,
    sign_mode: str = "uniform",
) -> tuple[dict[str, tuple[float, float]], float, float, float]:
    """Union +/-final_step Neighborhood review (memory version): p1 3 value combination of each
    axis + all zeros, axis-by-axis rotation score on the locked trace row to take the mean
    (0.2.199-patch29fi row format, equivalent to the full array score bit by bit -- patch29ff
    Verified row format score = full array score; no longer rotate the entire volume complex
    array combination by combination). Return (optimal phases, optimal score, fixed combination
    score, all-zero combination score)."""
    import itertools

    search_axes = [a for a in fixed]
    offsets = (-final_step, 0.0, final_step)
    combos: list[dict[str, tuple[float, float]]] = []
    for combo in itertools.product(offsets, repeat=len(search_axes)):
        phases = dict(fixed)
        for axis, offset in zip(search_axes, combo):
            p0, p1 = fixed[axis]
            phases[axis] = (p0, p1 + offset)
        combos.append(phases)
    all_zero = {axis: (0.0, 0.0) for axis in search_axes}
    combos.append(all_zero)

    # 0.2.199-patch29fi(user): Linearization -- only extract locked trace lines once per axis, and
    # then only rotate these lines for each combination to score (same path as search_axis_memory;
    # old score_axis_ memory rotation of the entire volume replication array + window-by-window
    # Python scoring each time, 3D NUS once joint took ~34-45.5s).
    axis_rows: dict[str, np.ndarray] = {}
    for axis in search_axes:
        idx, pos = axis_traces.get(axis, ([], []))
        if not idx or axis not in axis_arrays:
            continue
        arr = np.asarray(axis_arrays[axis], dtype=np.complex128)
        moved = np.moveaxis(arr, axis_index[axis], -1)
        flat = moved.reshape(-1, moved.shape[-1])
        axis_rows[axis] = flat[idx]

    def _score_combo(phases: dict[str, tuple[float, float]]) -> float:
        vals: list[float] = []
        for axis in search_axes:
            idx, pos = axis_traces.get(axis, ([], []))
            if not idx or axis not in axis_rows:
                continue
            p0, p1 = phases[axis]
            vals.append(
                score_locked_memory(
                    axis_rows[axis], pos, p0, p1, sign_mode=sign_mode
                )
            )
        return float(np.mean(vals)) if vals else -1.0

    best_phases = dict(fixed)
    best_score = -1.0
    fixed_score = -1.0
    zero_score = -1.0
    for phases in combos:
        s = _score_combo(phases)
        if phases == fixed:
            fixed_score = s
        if phases == all_zero:
            zero_score = s
        if s > best_score:
            best_score, best_phases = s, dict(phases)
    return best_phases, best_score, fixed_score, zero_score
