"""NMRPipe bruker workflow helpers: fid.com parameter parsing and the acqus cross-check.

Ported from NMRFlow processing/bruker_workflow.py and adapted to the NMRForge internal data model.
Used to verify and patch the fid.com that bruker -AUTO generates (acqus is the authoritative
parameter source).
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from core.data.internal_data_model import Experiment, SamplingMode
from ui_support.i18n import tr

_KEY_RE = re.compile(
    r"-(xN|yN|zN|xT|yT|zT|xSW|ySW|zSW|xOBS|yOBS|zOBS|xCAR|yCAR|zCAR|"
    r"xLAB|yLAB|zLAB|xMODE|yMODE|zMODE|decim|dspfvs|grpdly)\s+(\S+)"
)

_OUT_RE = re.compile(r"(-out\s+)(\S+)")


def _fnmode(experiment: Experiment, logical_axis: str) -> int:
    if experiment.ndim >= 3:
        mapping = {"F3": "acqus", "F2": "acqu2s", "F1": "acqu3s"}
    else:
        mapping = {"F2": "acqus", "F1": "acqu2s"}
    block = experiment.acquisition_parameters.get(mapping.get(logical_axis, ""), {})
    try:
        return int(block.get("FnMODE", 0) or 0)
    except (TypeError, ValueError):
        return 0


def _dim(experiment: Experiment, logical_axis: str):
    for dim in experiment.dimensions:
        if dim.logical_axis == logical_axis:
            return dim
    return None


def _effective_td(experiment: Experiment) -> list[int]:
    """The points per dimension used for conversion/verification: NusTD (the sampling grid) on NUS
    indirect dimensions, otherwise TD."""
    td = [dim.td for dim in experiment.dimensions]
    if experiment.sampling.mode is SamplingMode.NUS:
        for index, filename in ((1, "acqu2s"), (2, "acqu3s")):
            if len(td) <= index:
                continue
            block = experiment.acquisition_parameters.get(filename, {})
            try:
                nus_td = int(block.get("NusTD", 0) or 0)
            except (TypeError, ValueError):
                continue
            if nus_td:
                td[index] = nus_td
    return td


_NUSEXPAND_RE = re.compile(r"nusExpand\.tcl[^\n]*?-sampleCount\s+(\d+)")


def patch_nus_expand_count(text: str, nuslist_count: int) -> tuple[str, list[str]]:
    """Correct the -sampleCount of nusExpand.tcl to the real number of nuslist lines.

    For some datasets (e.g. acqu2s TD contradicting NusTD) bruker -AUTO misjudges the number of
    sampling points, so ser_full expands only a few slices and bruk2pipe hangs reading the data
    (measured 2026-08-11).
    """
    warnings: list[str] = []

    def replace(match: re.Match) -> str:
        current = int(match.group(1))
        if current == nuslist_count:
            return match.group(0)
        warnings.append(
            tr("sampleCount: fid.com={p0} → nuslist={p1} (corrected)", p0=current, p1=nuslist_count)
        )
        return match.group(0).replace(
            f"-sampleCount {current}", f"-sampleCount {nuslist_count}", 1
        )

    patched = _NUSEXPAND_RE.sub(replace, text)
    return patched, warnings


def parse_fid_com(text: str) -> dict[str, str]:
    """Extract the key bruk2pipe parameters from the fid.com generated by the bruker command."""
    return {match.group(1): match.group(2) for match in _KEY_RE.finditer(text)}


def _num(value: str) -> float | None:
    try:
        return float(value)
    except ValueError:
        return None


def expected_values(experiment: Experiment) -> dict[str, tuple[Any, float | None]]:
    """fid.com target parameters (value, tolerance): shared by cross_check_fid_com and
    patch_fid_com.

    String parameters (LAB/MODE) have a tolerance of None; N/T/decim/dspfvs match exactly;
    SW/OBS/CAR/
    grpdly use a tolerance of 1e-3.
    """
    td = _effective_td(experiment)
    x = _dim(experiment, "F2" if experiment.ndim == 2 else "F3")
    values: dict[str, tuple[Any, float | None]] = {
        "xN": (float(td[0]), 0.0),
        "xT": (float(td[0] // 2), 0.0),
        "xSW": (float(x.sw), 1e-3) if x else (None, 1e-3),
        "xOBS": (float(x.sf), 1e-3) if x else (None, 1e-3),
        "xCAR": (float(x.o1p), 1e-3) if x else (None, 1e-3),
        "xLAB": (x.nucleus, None) if x else ("", None),
        "xMODE": ("DQD", None),
    }
    if experiment.ndim >= 2 and len(td) > 1:
        y = _dim(experiment, "F1" if experiment.ndim == 2 else "F2")
        y_fnmode = _fnmode(experiment, y.logical_axis) if y else 0
        values.update(
            {
                "yN": (float(td[1]), 0.0),
                "yT": (float(td[1] // 2), 0.0),
                "ySW": (float(y.sw), 1e-3) if y else (None, 1e-3),
                "yOBS": (float(y.sf), 1e-3) if y else (None, 1e-3),
                "yCAR": (float(y.o1p), 1e-3) if y else (None, 1e-3),
                "yLAB": (y.nucleus, None) if y else ("", None),
                "yMODE": ("Echo-AntiEcho" if y_fnmode in (4, 6) else "Complex", None),
            }
        )
    if experiment.ndim >= 3 and len(td) > 2:
        z = _dim(experiment, "F1")
        values.update(
            {
                "zN": (float(td[2]), 0.0),
                "zT": (float(td[2] // 2), 0.0),
                "zSW": (float(z.sw), 1e-3) if z else (None, 1e-3),
                "zOBS": (float(z.sf), 1e-3) if z else (None, 1e-3),
                "zCAR": (float(z.o1p), 1e-3) if z else (None, 1e-3),
                "zLAB": (z.nucleus, None) if z else ("", None),
                "zMODE": ("Complex", None),
            }
        )
    acqus = experiment.acquisition_parameters.get("acqus", {})
    if acqus.get("DECIM"):
        values["decim"] = (float(acqus["DECIM"]), 0.0)
    if acqus.get("DSPFVS"):
        values["dspfvs"] = (float(acqus["DSPFVS"]), 0.0)
    if acqus.get("GRPDLY"):
        values["grpdly"] = (float(acqus["GRPDLY"]), 1e-3)
    return values


def cross_check_fid_com(
    fid_params: dict[str, str],
    experiment: Experiment,
) -> list[str]:
    """Check the fid.com parameters against the acqus/acqu2s metadata (including MODE/DSP flags);
    returns warnings for any difference."""
    warnings: list[str] = []
    for key, (desired, tolerance) in expected_values(experiment).items():
        if key not in fid_params:
            continue
        if isinstance(desired, str):
            if fid_params[key] != desired:
                warnings.append(f"{key}: fid.com={fid_params[key]} vs acqus={desired}")
            continue
        actual = _num(fid_params[key])
        if actual is None or desired is None:
            continue
        if abs(actual - desired) > (tolerance if tolerance is not None else 0.0):
            warnings.append(f"{key}: fid.com={fid_params[key]} vs acqus={desired:g}")
    return warnings


def _acqus_values(experiment: Experiment) -> dict[str, str]:
    values: dict[str, str] = {}
    for key, (desired, _tolerance) in expected_values(experiment).items():
        if desired is None:
            continue
        if isinstance(desired, str):
            values[key] = desired
        elif key in ("xSW", "ySW", "zSW", "xOBS", "yOBS", "zOBS", "xCAR", "yCAR", "zCAR"):
            values[key] = f"{desired:.3f}"
        elif key in ("decim", "dspfvs", "grpdly"):
            values[key] = f"{desired:g}"
        else:
            values[key] = str(int(desired))
    if experiment.sampling.mode is SamplingMode.NUS:
        # NUS: xN/xT is the ser row size nusExpand pads to via serPadSize (e.g. 908->1024), not the
        # acqus TD, so it must not be overridden (0.2.195); yN/yT/zN/zT are still corrected to the
        # NusTD grid and forced to agree with nusExpand
        values.pop("xN", None)
        values.pop("xT", None)
    return values


def patch_fid_com(
    text: str,
    experiment: Experiment,
) -> tuple[str, list[str]]:
    """Correct the fid.com parameters that disagree with acqus/acqu2s, and rename the single-file
    output from bruker default test.fid to {dataset_id}.fid
    (0.2.163-patch13: automatic and manual fid naming aligned, so the fid.com output name is final).

    Returns (the corrected text, the list of corrections).
    """
    target = _acqus_values(experiment)
    warnings: list[str] = []

    def replace(match: re.Match) -> str:
        key = match.group(1)
        current = match.group(2)
        desired = target.get(key)
        if desired is None or desired == "":
            return match.group(0)
        if current != desired:
            warnings.append(tr(
                "{p0}: fid.com={p1} → acqus={p2} "
                "(corrected)",
                p0=key,
                p1=current,
                p2=desired,
            ))
            return f"-{key} {desired}"
        return match.group(0)

    patched = _KEY_RE.sub(replace, text)
    # 0.2.199-patch23: drop the nusExpand -mask stage from fid.com -- SMILE only reads nuslist and
    # needs no mask, so it is simply not generated (rather than deleting the artifact after the
    # conversion). ser_full stays (it is bruk2pipe input).
    patched, mask_removed = _MASK_STAGE_RE.subn("", patched)
    if mask_removed:
        warnings.append(
            tr(
            "Removed the nusExpand -mask stage from fid.com (SMILE does not need a "
            "mask)",
        )
        )
    if experiment.sampling.mode is SamplingMode.NUS:
        patched, grid_warnings = _force_nus_expand_grid(patched, experiment)
        warnings += grid_warnings
        # 0.2.199-patch27: single-file output is not forced -- bruker decides the output shape (TD=1
        # single file, TD>1 slices) and the program accepts both (see the slicing fallback in
        # reconstruct_nus)
    patched, out_warnings = patch_fid_out_name(patched, experiment.dataset_id)
    warnings += out_warnings
    return patched, warnings


# 0.2.199-patch23: the whole mask stage of fid.com (nusExpand.tcl -mask, including the xyz2pipe line
# feeding it) is removed; both the single-file (-out ./mask.fid) and the older sliced form
# (-out ./mask/test%03d.fid) are supported.
  # Note: the continuation lines after the trailing backslash of the nusExpand line must go as
# well (do
  # not swallow the trailing backslash with a greedy [^\n]*, or the continuation group fails to
# match).
_MASK_STAGE_RE = re.compile(
    r"\n(?:[ \t]*\|?[ \t]*xyz2pipe -in [^\n]*? -noWr[ \t]*\\\n)?"
    r"[ \t]*\|?[ \t]*nusExpand\.tcl -mask[^\n]*"
    r"(?:\n[ \t][^\n]*)*"
)

_NUS_EXPAND_RE = re.compile(r"(nusExpand\.tcl[^\n]*?)\\\n")


def _force_nus_expand_grid(
    text: str, experiment: Experiment
) -> tuple[str, list[str]]:
    """Force nusExpand and bruk2pipe onto the same NusTD grid (0.2.195).

    nusExpand derives the grid from nuslist by default (yTNUS/zTNUS); when that disagrees with the
    NusTD-patched bruk2pipe (e.g. cc/63:83 vs 85) the fid is stored in the wrong place and the
    reconstruction is wrong; passing -yT/-zT explicitly puts both on one grid. Only the first
    (expansion) call is changed, the mask call is left alone.
    """
    td = _effective_td(experiment)
    grid: list[str] = []
    if len(td) > 1:
        grid.append(f"-yT {int(td[1] // 2)}")
    if len(td) > 2:
        grid.append(f"-zT {int(td[2] // 2)}")
    if not grid:
        return text, []
    warnings: list[str] = []

    def replace(match: re.Match) -> str:
        line = match.group(1)
        if "-yT" in line or "-zT" in line:
            return match.group(0)
        warnings.append(
            tr("nusExpand grid: forced ") + " ".join(grid) + tr(" (same as bruk2pipe)")
        )
        return line[:-1] + " " + " ".join(grid) + " \\\n"

    patched, _count = _NUS_EXPAND_RE.subn(replace, text, count=1)
    return patched, warnings


def patch_fid_out_name(text: str, dataset_id: str) -> tuple[str, list[str]]:
    """Rewrite the -out single-file name of fid.com to {dataset_id}.fid.

    The fid.com generated by bruker -AUTO always writes ./test.fid; after the rewrite fid.com
    produces
    the final name directly and neither the automatic nor the manual path has to rename it when
    moving
    it into place. The sliced output form (fid/test%03d.fid, 3D uniform/NUS) keeps bruker fixed
    behaviour -- the slice names already agree along the automatic and manual paths
    (test%03d.fid), so
    nothing is rewritten here. Returns (text, list of corrections).
    """
    warnings: list[str] = []

    def replace(match: re.Match) -> str:
        current = match.group(2)
        if "%" in current:
            return match.group(0)  # sliced form: keep bruker fixed naming
        name = Path(current).name
        if name != "test.fid":
            return match.group(0)
        prefix = current[: -len(name)]
        desired = f"{prefix}{dataset_id}.fid"
        warnings.append(tr("out: {p0} → {p1} (corrected)", p0=current, p1=desired))
        return f"{match.group(1)}{desired}"

    patched = _OUT_RE.sub(replace, text)
    # 0.2.199: after the main output test.fid is renamed, the `-in ./test.fid` of the mask stage is
  # renamed with it, otherwise a single-file output (some segmented data) would lose its input
    # there
    patched = re.sub(
        r"(-in\s+)(?:\./)?test\.fid\b",
        r"\g<1>" + f"{dataset_id}.fid",
        patched,
    )
    return patched, warnings


def apply_fid_com_overrides(
    text: str,
    overrides: dict[str, str],
) -> tuple[str, list[str]]:
    """Apply manual fid.com parameter overrides to the script (segment by segment for segmented
    data).

    The manual path exists only so people can tune parameters: what the user changed on the
    reference
    segment fid.com (the keys of parse_fid_com, e.g. ySW/-yCAR) is applied with the same values to
    every segment fid.com, while the backend still guarantees consistent conversion/slicing/merging.
    Existing parameters are replaced, never added. Returns (text, list of corrections).
    """
    seen: set[str] = set()
    warnings: list[str] = []

    def replace(match: re.Match) -> str:
        key = match.group(1)
        seen.add(key)
        desired = overrides.get(key)
        if desired is None:
            return match.group(0)
        current = match.group(2)
        if current != desired:
            warnings.append(tr(
                "{p0}: fid.com={p1} -> manual={p2} "
                "(applied)",
                p0=key,
                p1=current,
                p2=desired,
            ))
            return f"-{key} {desired}"
        return match.group(0)

    patched = _KEY_RE.sub(replace, text)
    for key in overrides:
        if key not in seen:
            warnings.append(
                tr(
                "{p0}: The corresponding parameter was not found in fid.com and has been "
                "skipped",
                p0=key,
            ))
    return patched, warnings
