"""NMRPipe script generates tests (deterministic + SOFTWARE_SUMMARY §6.2 parameter required)."""

from __future__ import annotations

from pathlib import Path

from backend.script_generator import (
    effective_td,
    generate_convert_script,
    generate_process_script,
)
from core.data.bruker_reader import read_dataset
from core.planning.method_selector import select_method


def _convert(exp) -> str:
    return generate_convert_script(exp)


def test_convert_script_2d_required_params(bruker_dir: Path) -> None:
    exp = read_dataset(bruker_dir / "hsqc_2d")
    script = _convert(exp)
    assert script.startswith("#!/bin/csh")
    assert "-xMODE DQD" in script
    assert "-yMODE Complex" in script
    assert "-ws 8" in script and "-noi2f" in script  # DSPFVS=21
    assert "-DMX" not in script
    assert "-aq2D 2" in script  # FnMODE 5
    assert "-xN 2048" in script
    assert "-yN 256" in script
    assert "-ndim 2" in script
    assert "\r" not in script  # LF End of line.


def test_convert_script_nus3d_td1_uses_nustd(bruker_dir: Path) -> None:
    """When acqu3s TD=1, zN must use NusTD (otherwise fid.com outputs a single file instead of a
    slice)."""
    exp = read_dataset(bruker_dir / "nus_3d")
    assert exp.ndim == 3
    assert exp.sampling.mode.value == "nus"
    td = effective_td(exp)
    assert td[2] == 128  # NusTD, not 1.
    assert td[1] == 48  # acqu2s NusTD
    script = _convert(exp)
    assert "-zN 128" in script
    assert __import__("re").search(r"-zN 1(?![0-9])", script) is None
    assert "-yN 48" in script
    assert "-ndim 3" in script
    assert "-yMODE Complex" in script  # F2=acqu2s FnMODE=5
    assert "-zMODE Complex" in script


def test_convert_script_echo_antiecho_mode(bruker_dir: Path) -> None:
    exp = read_dataset(bruker_dir / "hsqc_2d")
    exp.acquisition_parameters["acqu2s"]["FnMODE"] = 6
    script = _convert(exp)
    assert "-yMODE Echo-AntiEcho" in script  # F1 FnMODE=6(Official enumeration E-A).
    assert "-aq2D 3" in script  # FnMODE 6 → 3


def test_nus_direct_window_always_sp() -> None:
    """0.2.199-patch11: direct dimension window fixed SP (SMILE requires direct dimension
    apodisation and tail attenuation)."""
    from backend.script_generator import _nus_direct_window_line

    assert "SP" in _nus_direct_window_line(None, 2)
    assert "SP" in _nus_direct_window_line({"type": "none"}, 2)
    assert "SP" in _nus_direct_window_line(
        {"type": "gaussian", "g1": 8.0, "g2": 15.0}, 2
    )
    assert "SP" in _nus_direct_window_line({"type": "exp", "lb": 5.0}, 1)
    sb = _nus_direct_window_line(
        {"type": "sine_bell", "off": 0.5, "end": 0.98, "pow": 2, "c": 0.5},
        2,
    )
    assert "SP -off 0.5" in sb


def test_real_modes_nus_rejected(bruker_dir: Path) -> None:
    """SMILE(NUS) path explicitly rejects real indirect dimension (reconstruction only supports
    complex encoding). The FnMODE generated by Bruker NUS sampler is always States-TPPI/Echo-
    Antiecho; TPPI/QSEQ/QF has no quadrature information, SMILE -nDim 3 cannot be reconstructed,
    and an error is reported at the entrance to prevent silent generation of complex script (the
    uniform path already supports these modes)."""
    from backend.script_generator import (
        generate_3d_nus_script,
        generate_nus_finalize_script,
    )

    exp = read_dataset(bruker_dir / "hsqc_2d")
    exp.acquisition_parameters["acqu2s"]["FnMODE"] = 3  # TPPI
    import pytest

    with pytest.raises(NotImplementedError, match="real/magnitude"):
        generate_nus_finalize_script(exp, planes="recon.ft1", out_file="e.ft2")
    exp3 = read_dataset(bruker_dir / "nus_3d")
    exp3.acquisition_parameters["acqu3s"]["FnMODE"] = 1  # QF
    with pytest.raises(NotImplementedError, match="FnMODE=1"):
        generate_3d_nus_script(
            exp3, in_file="e.fid", nuslist="nuslist", out_file="e.ft3"
        )


def test_real_modes_uniform_scripts(bruker_dir: Path) -> None:
    """Uniform path generates correct script for real/magnitude mode (TPPI/QSEQ/QF). Based
    on:NMRPipe official template (bruk2pipe ACQUISITION MODES + notilt2.com magnitude example)
    -- TPPI -> -yMODE TPPI/-aq2D 1/FT -real;QSEQ -> -yMODE Sequential/-aq2D 2/FT -bruk;QF ->
    -yMODE Real/-aq2D 0/FT+MC. real class -yT does not divide by 2(notilt2.com -yT ySize).
    magnitude has no phase node."""
    td_y = None
    for mode, mode_kw, aq2d, ft_line, has_mc in (
        (3, "-yMODE TPPI", "-aq2D 1", "| nmrPipe -fn FT -real \\", False),
        (2, "-yMODE Sequential", "-aq2D 2", "| nmrPipe -fn FT -bruk \\", False),
        (1, "-yMODE Real", "-aq2D 0", "| nmrPipe -fn FT \\", True),
    ):
        exp = read_dataset(bruker_dir / "hsqc_2d")
        td_y = int(exp.acquisition_parameters["acqu2s"]["TD"])
        exp.acquisition_parameters["acqu2s"]["FnMODE"] = mode
        plan = select_method(exp)
        script = generate_process_script(
            exp, plan, in_file="a.fid", out_file="a.ft2"
        )
        assert ft_line in script, (mode, ft_line)
        assert ("| nmrPipe -fn MC \\" in script) == has_mc, mode
        # Only direct dimension PS.
        assert script.count("| nmrPipe -fn PS") == (1 if mode == 1 else 2)
        conv = _convert(exp)
        assert mode_kw in conv, (mode, mode_kw)  # Convert MODE keyword.
        assert aq2d in conv, (mode, aq2d)
        assert f"-yT {td_y}" in conv  # real Class -yT does not divide by 2.
        assert "-yT " + str(td_y // 2) not in conv
    assert td_y is not None


def test_convert_script_states_mode(bruker_dir: Path) -> None:
    """Official enumeration FnMODE=4=States: Conversion is still Complex + aq2D States(2)."""
    exp = read_dataset(bruker_dir / "hsqc_2d")
    exp.acquisition_parameters["acqu2s"]["FnMODE"] = 4
    script = _convert(exp)
    assert "-yMODE Complex" in script  # States Non-Echo-AntiEcho.
    assert "-aq2D 2" in script  # FnMODE 4 → 2


def test_convert_script_3d_y_mode_from_acqu2s(bruker_dir: Path) -> None:
    exp = read_dataset(bruker_dir / "hnca_3d")
    script = _convert(exp)
    assert "-yMODE Complex" in script  # F2=acqu2s FnMODE=5
    assert "-aq2D 2" in script  # FnMODE 5 → 2


def test_process_script_2d(bruker_dir: Path) -> None:
    exp = read_dataset(bruker_dir / "hsqc_2d")
    plan = select_method(exp)
    script = generate_process_script(exp, plan, in_file="test.fid", out_file="out.ft2")
    assert "xyz2pipe -in test.fid -x" in script
    assert "| nmrPipe -fn SP" in script
    assert "| nmrPipe -fn ZF" in script
    assert "| nmrPipe -fn FT" in script
    assert "| nmrPipe -fn PS" in script
    # After direct dimension + after indirect dimension (transposed back).
    assert script.count("| nmrPipe -fn TP") == 2
    assert "| pipe2xyz -out out.ft2 -x" in script
    assert "\r" not in script


def test_process_script_3d_two_tps(bruker_dir: Path) -> None:
    exp = read_dataset(bruker_dir / "hnca_3d")
    plan = select_method(exp)
    script = generate_process_script(exp, plan, in_file="test.fid", out_file="out.ft3")
    assert script.count("| nmrPipe -fn TP") == 2
    assert "| pipe2xyz -out out.ft3 -x" in script
    # 3D single pass: complement ZTP, move slow dimension (F1) to FT axis + end TP, output (F2, F1,
    # F3) layout.
    assert script.count("| nmrPipe -fn ZTP") == 1
    # 3D first indirect dimension F2(acqu2s FnMODE=5 States-TPPI) -> FT -alt -neg; second indirect
    # dimension F1(acqu3s FnMODE=4 States) -> FT No flag.
    assert "| nmrPipe -fn FT -alt -neg" in script
    assert "| nmrPipe -fn FT -alt \\" not in script
    assert "| nmrPipe -fn FT \\" in script


def test_scripts_deterministic(bruker_dir: Path) -> None:
    exp = read_dataset(bruker_dir / "hsqc_2d")
    plan = select_method(exp)
    assert _convert(exp) == _convert(exp)
    assert generate_process_script(exp, plan, in_file="a.fid", out_file="a.ft2") == (
        generate_process_script(exp, plan, in_file="a.fid", out_file="a.ft2")
    )


def test_preview_script_2d_f2_keeps_complex(bruker_dir: Path) -> None:
    """F2 preview: F2 PS does not add -di, indirect dimension F1 adds -di, zero filling."""
    exp = read_dataset(bruker_dir / "hsqc_2d")
    plan = select_method(exp)
    from backend.script_generator import generate_preview_script

    script = generate_preview_script(
        exp, plan, in_file="test.fid", out_file="p_F2.ft2", preview_axis="F2"
    )
    assert "| nmrPipe -fn PS -p0 0 -p1 0 \\" in script  # F2 Do not add -di.
    assert "| nmrPipe -fn PS -p0 0 -p1 0 -di \\" in script  # F1 Add -di.
    assert "| nmrPipe -fn ZF" not in script  # Zero zero filling (same as old phase candidate).
    assert script.count("| nmrPipe -fn PS") == 2
    assert script.count("| nmrPipe -fn POLY") == 1  # Search axis F2 skip POLY.
    assert "| pipe2xyz -out p_F2.ft2 -x" in script


def test_preview_script_2d_f1_fixed_phases_only_other_axes(bruker_dir: Path) -> None:
    """F1 preview: preview_axis keeps PS(0,0) by itself without adding -di; fixed phase only acts
    on other axes."""
    exp = read_dataset(bruker_dir / "hsqc_2d")
    plan = select_method(exp)
    from backend.script_generator import generate_preview_script

    script = generate_preview_script(
        exp,
        plan,
        in_file="test.fid",
        out_file="p_F1.ft2",
        preview_axis="F1",
        fixed_phases={"F1": (10.0, -2.0), "F2": (5.0, 0.0)},
    )
    # Preview axis F1 must be PS(0,0) None -di; the incoming F1 fixed phase shall not be applied.
    assert "| nmrPipe -fn PS -p0 0 -p1 0 \\" in script
    assert "| nmrPipe -fn PS -p0 5 -p1 0 -di \\" in script  # F2 Fixed phase application.
    assert "p0 10" not in script
    assert script.count("| nmrPipe -fn POLY") == 1  # Search axis F1 skip POLY.


def test_preview_script_3d(bruker_dir: Path) -> None:
    """3D F2 preview: F3/F1 adds -di, F2 does not add; zero zero filling; 2 TP."""
    exp = read_dataset(bruker_dir / "hnca_3d")
    plan = select_method(exp)
    from backend.script_generator import generate_preview_script

    script = generate_preview_script(
        exp, plan, in_file="test.fid", out_file="p_F2.ft3", preview_axis="F2"
    )
    assert script.count("| nmrPipe -fn PS") == 3
    assert script.count("| nmrPipe -fn PS -p0 0 -p1 0 -di \\") == 2
    assert "| nmrPipe -fn PS -p0 0 -p1 0 \\" in script
    assert script.count("| nmrPipe -fn TP") == 2
    assert script.count("| nmrPipe -fn ZTP") == 1  # Slow dimension ZTP + end TP -> (F2,F1,F3).
    assert "| nmrPipe -fn ZF" not in script
    assert script.count("| nmrPipe -fn POLY") == 2  # Search axis F2 skip POLY.


def test_2d_nus_script(bruker_dir: Path) -> None:
    """Two stages: stage1 nmrPipe -in + SMILE(-sample None,-xT complex point grid); stage2 nmrPipe
    -in recon.ft1 + FT -alt + -out -ov."""
    exp = read_dataset(bruker_dir / "nus_2d")
    from backend.script_generator import generate_2d_nus_script

    script = generate_2d_nus_script(
        exp, in_file="exp.fid", nuslist="nuslist", out_file="exp.ft2",
        nuslist_count=5, ext_lo="9.0", ext_hi="7.5", nsigma=7.0, thresh=0.85,
    )
    assert script.startswith("#!/bin/csh")
    assert "nmrPipe -in exp.fid \\" in script
    assert "| nmrPipe -fn SMILE -nDim 2" in script
    # If there is a sampling schedule, explicitly hand it over to SMILE (same for 2D single file).
    assert "-sample nuslist" in script
    assert "-sample None" in generate_2d_nus_script(
        exp, in_file="exp.fid", nuslist="", out_file="exp.ft2"
    )
    assert "-sampleCount 5" in script
    assert "-maxIter 1500" in script  # 5/128=3.9% -> Lowest grade 1500.
    # Ordinary experiments do not add the cross parameter parameter (only CT experiments add it).
    assert "-xCT" not in script
    assert "-thresh 0.85" in script
    assert "-x1 9.0ppm -xn 7.5ppm" in script
    assert "-xT 128" in script  # F1 Complex Point Grid 256//2.
    assert "| nmrPipe -fn FT -alt \\" in script  # States Indirect dimension.
    assert "nmrPipe -in nus2d/recon.ft1 \\" in script
    assert "  -out exp.ft2 -ov" in script
    assert "| pipe2xyz -out exp.ft2" not in script
    assert "\r" not in script
def test_smile_max_iter_tiers() -> None:
    """0.2.137:SMILE -maxIter binning by sampling rate (>0.5->300,>0.3->600, >0.15->1000, the
    remaining 1500)."""
    from backend.script_generator import smile_max_iter

    assert smile_max_iter(0.6) == 300
    assert smile_max_iter(0.5) == 600  # Bounds:>0.5 only 300.
    assert smile_max_iter(0.4) == 600
    assert smile_max_iter(0.3) == 1000  # Bounds:>0.3 only 600.
    assert smile_max_iter(0.2) == 1000
    assert smile_max_iter(0.15) == 1500  # Bounds:>0.15 only 1000.
    assert smile_max_iter(0.0) == 1500


def test_smile_cross_term_args_only_by_ct(bruker_dir: Path) -> None:
    """0.2.138:-xCT/-yCT Whether to add or not is only determined by whether CT is tested (it has
    nothing to do with the sampling rate)."""
    exp2 = read_dataset(bruker_dir / "nus_2d")
    exp3 = read_dataset(bruker_dir / "nus_3d")
    from backend.script_generator import smile_cross_term_args

    assert smile_cross_term_args(exp2) == ""  # Ordinary 2D does not add.
    assert smile_cross_term_args(exp3) == ""  # Ordinary 3D does not add.
    # Constant-time: indirect dimension explicitly turns off intersection terms.
    exp2.acquisition_parameters.setdefault("acqus", {})["PULPROG"] = (
        "hsqcctetgpsp.2"
    )
    assert smile_cross_term_args(exp2) == "-xCT 1 "
    exp3.acquisition_parameters.setdefault("acqus", {})["PULPROG"] = (
        "cthsqcetgp.2"
    )
    assert smile_cross_term_args(exp3) == "-xCT 1 -yCT 1 "


def test_3d_nus_script_max_iter_by_sampling(bruker_dir: Path) -> None:
    """-maxIter changes with the sampling rate: 0.6->300, 0.1->1500; no count fallback metadata
    sf."""
    exp = read_dataset(bruker_dir / "nus_3d")
    from backend.script_generator import effective_td, generate_3d_nus_script

    td = effective_td(exp)
    grid = int(td[1]) * int(td[2])
    base = dict(in_file="e.fid", nuslist="nuslist", out_file="e.ft3")
    assert "-maxIter 300" in generate_3d_nus_script(exp, **base)  # sf=1.0 Rollback.
    hi = generate_3d_nus_script(exp, nuslist_count=int(grid * 0.6), **base)
    assert "-maxIter 300" in hi
    assert "-xCT" not in hi  # Ordinary experiments (not CT) do not add cross-term parameter.
    lo = generate_3d_nus_script(
        exp, nuslist_count=max(1, int(grid * 0.1)), **base
    )
    assert "-maxIter 1500" in lo
    assert "-xCT" not in lo  # Ordinary experiments (not CT) do not add cross-term parameter.
    exp.acquisition_parameters.setdefault("acqus", {})["PULPROG"] = (
        "cthsqcetgp.2"
    )
    ct = generate_3d_nus_script(exp, nuslist_count=int(grid * 0.8), **base)
    # Experiment with high sampling to also turn off cross terms.
    assert "-xCT 1 -yCT 1 -thresh" in ct


def test_smile_max_mem_optional(bruker_dir: Path) -> None:
    """0.2.199-patch14:-maxMem is passed in by the caller based on available memory; this line is
    not generated by default."""
    exp2 = read_dataset(bruker_dir / "nus_2d")
    exp3 = read_dataset(bruker_dir / "nus_3d")
    from backend.script_generator import (
        generate_2d_nus_script,
        generate_3d_nus_script,
    )

    base2 = dict(in_file="e.fid", nuslist="nuslist", out_file="e.ft2")
    base3 = dict(in_file="e.fid", nuslist="nuslist", out_file="e.ft3")
    assert "-maxMem" not in generate_2d_nus_script(exp2, **base2)
    assert "-maxMem" not in generate_3d_nus_script(exp3, **base3)
    s2 = generate_2d_nus_script(exp2, max_mem=12.0, **base2)
    s3 = generate_3d_nus_script(exp3, max_mem=12.0, **base3)
    assert "-maxMem 12" in s2
    assert "-maxMem 12" in s3


def test_nus_finalize_script_2d(bruker_dir: Path) -> None:
    """Reconstruction plane finalization (2D): nmrPipe -in + FT -alt + POLY + -out -ov, dimension
    by dimension PS can be configured."""
    exp = read_dataset(bruker_dir / "nus_2d")
    from backend.script_generator import generate_nus_finalize_script

    script = generate_nus_finalize_script(
        exp, planes="nus2d/recon.ft1", out_file="e.ft2"
    )
    assert "nmrPipe -in nus2d/recon.ft1 \\" in script
    assert "| nmrPipe -fn FT -alt \\" in script
    assert "| nmrPipe -fn PS -p0 0 -p1 0 -di" in script
    assert "| nmrPipe -fn POLY -auto" in script  # Consistent with verification s2.com.
    assert "  -out e.ft2 -ov" in script
    assert "| nmrPipe -fn SMILE" not in script  # No rerun SMILE.
    phased = generate_nus_finalize_script(
        exp, planes="nus2d/recon.ft1", out_file="e.ft2",
        phases={"F1": (12.0, -3.0)},
    )
    assert "| nmrPipe -fn PS -p0 12 -p1 -3 -di" in phased
    # Indirect dimension (F1) does not add -neg (different from 3D F2 rules).
    assert "-neg" not in phased
def test_nus_finalize_script_3d(bruker_dir: Path) -> None:
    exp = read_dataset(bruker_dir / "nus_3d")
    from backend.script_generator import generate_nus_finalize_script

    phased = generate_nus_finalize_script(
        exp, planes="nus3d_rc/test%04d.ft1", out_file="e.ft3",
        phases={"F2": (12.0, -3.0), "F1": (5.0, 2.0)},
    )
    assert "xyz2pipe -in nus3d_rc/test%04d.ft1 -x" in phased
    assert "| nmrPipe -fn PS -p0 12 -p1 -3 -di" in phased
    assert "| nmrPipe -fn PS -p0 5 -p1 2 -di" in phased
    assert phased.count("| nmrPipe -fn TP") == 2
    # F2(acqu2s FnMODE=5 States-TPPI) -> FT -alt -neg;F1(acqu3s FnMODE=4 States) -> No flag.
    assert "| nmrPipe -fn FT -alt -neg" in phased
    assert "| nmrPipe -fn FT -alt \\" not in phased
    assert "| nmrPipe -fn FT \\" in phased


def test_2d_nus_script_extract_off(bruker_dir: Path) -> None:
    """When extract=False, do not write the EXT line; True to maintain the status quo (default 6-11
    ppm)."""
    exp = read_dataset(bruker_dir / "nus_2d")
    from backend.script_generator import generate_2d_nus_script

    on = generate_2d_nus_script(
        exp, in_file="e.fid", nuslist="nuslist", out_file="e.ft2"
    )
    assert "| nmrPipe -fn EXT" in on
    assert "-x1 10.5ppm -xn 6.5ppm" in on
    off = generate_2d_nus_script(
        exp, in_file="e.fid", nuslist="nuslist", out_file="e.ft2",
        extract=False,
    )
    assert "| nmrPipe -fn EXT" not in off


def test_3d_nus_script_extract_off(bruker_dir: Path) -> None:
    exp = read_dataset(bruker_dir / "nus_3d")
    from backend.script_generator import generate_3d_nus_script

    off = generate_3d_nus_script(
        exp, in_file="e.fid", nuslist="nuslist", out_file="e.ft3",
        extract=False,
    )
    assert "| nmrPipe -fn EXT" not in off
    on = generate_3d_nus_script(
        exp, in_file="e.fid", nuslist="nuslist", out_file="e.ft3"
    )
    assert "| nmrPipe -fn EXT" in on


def test_3d_nus_script(bruker_dir: Path) -> None:
    exp = read_dataset(bruker_dir / "nus_3d")
    from backend.script_generator import generate_3d_nus_script

    script = generate_3d_nus_script(
        exp, in_file="exp.fid", nuslist="nuslist", out_file="exp.ft3",
        nuslist_count=4, ext_lo="9.0", ext_hi="7.5",
    )
    assert "-fn SMILE -nDim 3" in script
    assert "-sample nuslist" in script
    assert "| pipe2xyz -out exp.ft3 -x" in script
    assert script.count("| nmrPipe -fn TP") == 2
    assert "\r" not in script
    # F2(acqu2s FnMODE=5 States-TPPI) -> FT -alt -neg;F1(acqu3s FnMODE=4 States) -> No flag.
    assert "| nmrPipe -fn FT -alt -neg" in script
    assert "| nmrPipe -fn FT -alt \\" not in script
    assert "| nmrPipe -fn FT \\" in script
    assert generate_3d_nus_script(
        exp, in_file="exp.fid", nuslist="nuslist", out_file="exp.ft3"
    ) == generate_3d_nus_script(
        exp, in_file="exp.fid", nuslist="nuslist", out_file="exp.ft3"
    )


def test_3d_nus_script_smile_tuning(bruker_dir: Path) -> None:
    exp = read_dataset(bruker_dir / "nus_3d")
    from backend.script_generator import generate_3d_nus_script

    script = generate_3d_nus_script(
        exp, in_file="exp.fid", nuslist="nuslist", out_file="exp.ft3",
        nsigma=5.0, thresh=0.99, smile_scaling=True, smile_report=2,
    )
    assert "-nSigma 5" in script
    assert "-thresh 0.99" in script
    # Without window (window is taken care of by step3 post-processing).
    assert "-xApod" not in script
    assert "-xP0" not in script    # SMILE Without phase modulation (step3 PS assumes).
    assert "-xAlt -xNeg" in script  # F2=States-TPPI:Consistent with step3 FT -alt -neg.
    assert "-yNeg" not in script  # F1=States:No directional sign.
    assert "-yAlt" not in script  # F1=States:No directional sign.
    assert "-scaling 1" in script
    assert "-report 2" in script


def test_select_smile_params_is_one_tier_for_every_fraction() -> None:
    from backend.script_generator import select_smile_params

    assert select_smile_params(0.04) == (5.0, 0.95)
    assert select_smile_params(0.3) == (5.0, 0.95)
    assert select_smile_params(0.8) == (5.0, 0.95)


def test_3d_nus_script_default_smile_params(bruker_dir: Path) -> None:
    exp = read_dataset(bruker_dir / "nus_3d")
    from backend.script_generator import generate_3d_nus_script

    script = generate_3d_nus_script(
        exp, in_file="exp.fid", nuslist="nuslist", out_file="exp.ft3"
    )
    # Without window (window is taken care of by step3 post-processing).
    assert "-xApod" not in script
    assert "-xP0" not in script    # SMILE Without phase modulation (step3 PS assumes).
    assert "-xAlt -xNeg" in script  # F2=States-TPPI:Consistent with step3 FT -alt -neg.
    assert "-yNeg" not in script  # F1=States:No directional sign.
    assert "-yAlt" not in script  # F1=States:No directional sign.
    assert "-scaling 1" in script


def test_smile_direction_flags_match_step3(bruker_dir: Path) -> None:
    """SMILE The direction flag in the command has the same origin as the step3 FT line (same as
    _FT_FLAGS + sampling coverage): nus_3d fixture's F2=States-TPPI(5) is -xAlt -xNeg and step3
    FT -alt -neg; F1=States(4) has no y flag and step3 FT No flag; 2D F1=5 is -xAlt and finally
    FT -alt; flip_f1 overwrites SMILE in sync with step3."""
    from backend.script_generator import generate_2d_nus_script, generate_3d_nus_script

    exp3 = read_dataset(bruker_dir / "nus_3d")
    s = generate_3d_nus_script(
        exp3, in_file="e.fid", nuslist="nuslist", out_file="e.ft3"
    )
    assert "-xAlt -xNeg" in s and "| nmrPipe -fn FT -alt -neg" in s
    assert "-yNeg" not in s and "-yAlt" not in s
    s = generate_3d_nus_script(
        exp3, in_file="e.fid", nuslist="nuslist", out_file="e.ft3",
        sampling={"flip_f1": True},
    )
    assert "-yNeg" in s and "| nmrPipe -fn FT -neg" in s  # F1 Flip sync.
    exp2 = read_dataset(bruker_dir / "hsqc_2d")
    s2 = generate_2d_nus_script(
        exp2, in_file="e.fid", nuslist="nuslist", out_file="e.ft2"
    )
    assert "-xAlt" in s2 and "| nmrPipe -fn FT -alt" in s2
    assert "-xNeg" not in s2


def test_process_script_direct_phase(bruker_dir: Path) -> None:
    exp = read_dataset(bruker_dir / "hsqc_2d")
    plan = select_method(exp)
    script = generate_process_script(
        exp, plan, in_file="a.fid", out_file="a.ft2",
        direct_phase={"F2": (12.0, -3.0)},
    )
    assert "| nmrPipe -fn PS -p0 12 -p1 -3 -di \\" in script


def test_3d_nus_script_direct_phase(bruker_dir: Path) -> None:
    exp = read_dataset(bruker_dir / "nus_3d")
    from backend.script_generator import generate_3d_nus_script

    script = generate_3d_nus_script(
        exp, in_file="e.fid", nuslist="nuslist", out_file="e.ft3",
        direct_phase=(12.0, -3.0),
    )
    assert "| nmrPipe -fn PS -p0 12 -p1 -3 -di \\" in script



def test_process_script_ext_default_6_11(bruker_dir: Path) -> None:
    """Process script direct dimension FT followed by EXT, the default selection is 6-11 ppm (after
    PS, before TP)."""
    exp = read_dataset(bruker_dir / "hsqc_2d")
    plan = select_method(exp)
    script = generate_process_script(exp, plan, in_file="a.fid", out_file="a.ft2")
    lines = script.splitlines()
    ps_index = next(
        i for i, line in enumerate(lines) if "| nmrPipe -fn PS" in line
    )
    ext_index = next(
        i for i, line in enumerate(lines) if "| nmrPipe -fn EXT" in line
    )
    tp_index = next(
        i for i, line in enumerate(lines) if "| nmrPipe -fn TP" in line
    )
    assert ps_index < ext_index < tp_index
    assert "| nmrPipe -fn EXT -x1 10.5ppm -xn 6.5ppm -sw -round 2" in script


def test_process_script_extract_disabled_and_custom(bruker_dir: Path) -> None:
    exp = read_dataset(bruker_dir / "hsqc_2d")
    plan = select_method(exp)
    off = generate_process_script(
        exp, plan, in_file="a.fid", out_file="a.ft2", extract=False
    )
    assert "| nmrPipe -fn EXT" not in off
    custom = generate_process_script(
        exp, plan, in_file="a.fid", out_file="a.ft2",
        ext_lo="9.0", ext_hi="7.5",
    )
    assert "| nmrPipe -fn EXT -x1 9.0ppm -xn 7.5ppm" in custom



def test_process_script_baseline_default_and_overrides(bruker_dir: Path) -> None:
    """Default is POLY -auto; baseline Configuration can be turned off/change order per
    dimension."""
    exp = read_dataset(bruker_dir / "hsqc_2d")
    plan = select_method(exp)
    default = generate_process_script(exp, plan, in_file="a.fid", out_file="a.ft2")
    assert default.count("| nmrPipe -fn POLY -auto") == 2  # F2 + F1
    off = generate_process_script(
        exp, plan, in_file="a.fid", out_file="a.ft2",
        baseline={"F2": {"enabled": False}},
    )
    assert off.count("| nmrPipe -fn POLY") == 1
    ordered = generate_process_script(
        exp, plan, in_file="a.fid", out_file="a.ft2",
        baseline={"F1": {"mode": "order", "order": 2}},
    )
    assert "| nmrPipe -fn POLY -ord 2" in ordered


def test_2d_nus_script_baseline_insert(bruker_dir: Path) -> None:
    """Two-stage baseline: stage1 F2 POLY is after EXT, stage2 F1 POLY is after PS."""
    exp = read_dataset(bruker_dir / "nus_2d")
    from backend.script_generator import generate_2d_nus_script

    script = generate_2d_nus_script(
        exp, in_file="e.fid", nuslist="nuslist", out_file="e.ft2"
    )
    assert script.count("| nmrPipe -fn POLY -auto") == 2
    stage2 = script.split("# stage 2:")[1].splitlines()
    ps_i = next(i for i, line in enumerate(stage2) if "| nmrPipe -fn PS" in line)
    assert "| nmrPipe -fn POLY" in stage2[ps_i + 1]
    off = generate_2d_nus_script(
        exp, in_file="e.fid", nuslist="nuslist", out_file="e.ft2",
        baseline={"F1": {"enabled": False}},
    )
    assert off.count("| nmrPipe -fn POLY") == 1
def test_3d_nus_script_baseline_insert(bruker_dir: Path) -> None:
    """NUS 3D: insert POLY after direct dimension EXT + F2/F1 after each PS (3 lines in total)."""
    exp = read_dataset(bruker_dir / "nus_3d")
    from backend.script_generator import generate_3d_nus_script

    script = generate_3d_nus_script(
        exp, in_file="e.fid", nuslist="nuslist", out_file="e.ft3"
    )
    assert script.count("| nmrPipe -fn POLY -auto") == 3

def test_effective_td_2d_nus_complex_grid(bruker_dir: Path) -> None:
    """2D NUS: F1 is not accepted when using complex point mesh TD//mult; acqu2s NusTD=TD."""
    exp = read_dataset(bruker_dir / "nus_2d")
    exp.acquisition_parameters["acqu2s"]["NusTD"] = 256  # Partial data NusTD=TD.
    from backend.script_generator import effective_td

    td = effective_td(exp)
    assert td[1] == 128  # 256 // 2 (States)
    exp3 = read_dataset(bruker_dir / "nus_3d")
    td3 = effective_td(exp3)
    assert td3[1] == 48 and td3[2] == 128  # 3D Keep NusTD (already a complex point number).

def test_process_script_window_and_zero_fill_overrides(
    bruker_dir: Path,
) -> None:
    """Window function/zero filling override: GM(g1/g2) window replacement SP; omit the ZF line
    when F1 does not have zero filling."""
    exp = read_dataset(bruker_dir / "hsqc_2d")
    plan = select_method(exp)
    from backend.script_generator import generate_process_script

    script = generate_process_script(
        exp,
        plan,
        in_file="a.fid",
        out_file="a.ft2",
        window={"F2": {"type": "gaussian", "g1": 4.0, "g2": 0.2}},
        zero_fill={"F1": {"mode": "none"}},
    )
    assert "| nmrPipe -fn GM -g1 4 -g2 0.2 \\" in script
    assert script.count("| nmrPipe -fn SP") == 1  # F1 Still the default SP.
    # F1 does not have zero filling: there is no ZF line after FT (F2 still retains the default 2 x
    # TD zero filling).
    assert script.count("| nmrPipe -fn ZF") == 1
    off = generate_process_script(
        exp,
        plan,
        in_file="a.fid",
        out_file="a.ft2",
        zero_fill={"F2": {"mode": "none"}, "F1": {"mode": "none"}},
    )
    assert "| nmrPipe -fn ZF" not in off


def _pow2_ge(value: int) -> int:
    return 1 << max(0, int(value) - 1).bit_length()


def test_zero_fill_plan_direct_and_indirect(bruker_dir: Path) -> None:
    """Direct dimension SI=2 x TD; indirect dimension is dynamic by target numerical resolution and
    constrained by 1/AQ (0.2.39)."""
    exp = read_dataset(bruker_dir / "hsqc_2d")
    from backend.script_generator import effective_td, zero_fill_plan

    td = effective_td(exp)
    plan = zero_fill_plan(exp)
    # Direct dimension: 2 x TD raised to the power of 2.
    assert plan["F2"]["size"] == _pow2_ge(2 * td[0])
    # Indirect dimension: not less than TD, not more than next_pow2(2 x TD)(points_per_line default
    # 2).
    assert td[1] <= plan["F1"]["size"] <= _pow2_ge(2 * td[1])
    # The narrower the line width, the more zero filling there is (wide line 60 Hz widens the target
    # point distance, SI decreases).
    narrow = zero_fill_plan(exp, linewidth_hz={"F1": 5.0})
    wide = zero_fill_plan(exp, linewidth_hz={"F1": 60.0})
    assert narrow["F1"]["size"] >= wide["F1"]["size"]
    # Override semantics: 0=auto; int k= indirect dimension k x TD; axis-by-axis none off.
    assert zero_fill_plan(exp, 0) == zero_fill_plan(exp)
    fixed = zero_fill_plan(exp, 2)
    assert fixed["F2"]["size"] == _pow2_ge(2 * td[0])
    assert fixed["F1"]["size"] == _pow2_ge(2 * td[1])
    off = zero_fill_plan(exp, {"F1": {"mode": "none"}})
    assert off["F1"]["mode"] == "none" and off["F1"]["size"] is None
    assert off["F2"]["size"] == plan["F2"]["size"]


def test_2d_nus_script_zero_fill_plan(bruker_dir: Path) -> None:
    """NUS Two-stage ZF scheme using zero filling: direct dimension 2 x TD, indirect dimension by
    reconstruction mesh dynamics."""
    exp = read_dataset(bruker_dir / "nus_2d")
    from backend.script_generator import (
        effective_td,
        generate_2d_nus_script,
        zero_fill_plan,
    )

    plan = zero_fill_plan(exp)
    script = generate_2d_nus_script(
        exp, in_file="e.fid", nuslist="nuslist", out_file="e.ft2"
    )
    assert f"| nmrPipe -fn ZF -zf -size {plan['F2']['size']} \\" in script
    assert f"| nmrPipe -fn ZF -size {plan['F1']['size']} \\" in script
    # NUS indirect dimension takes the complex point grid after reconstruction as TD (independent of
    # SMILE reconstruction).
    td = effective_td(exp)
    assert plan["F1"]["size"] >= td[1]
    # Indirect dimension is closed: stage2 no longer outputs the ZF line.
    off = generate_2d_nus_script(
        exp,
        in_file="e.fid",
        nuslist="nuslist",
        out_file="e.ft2",
        zero_fill={"F1": {"mode": "none"}},
    )
    assert "| nmrPipe -fn ZF -size" not in off
    assert "| nmrPipe -fn ZF -zf -size" in off  # Direct dimension reserved.


def test_finalize_script_zero_fill_plan(bruker_dir: Path) -> None:
    """The indirect dimension ZF of finalize (phase optimisation reuse) uses plan SI and can be
    turned off."""
    exp = read_dataset(bruker_dir / "nus_2d")
    from backend.script_generator import (
        generate_nus_finalize_script,
        zero_fill_plan,
    )

    plan = zero_fill_plan(exp)
    script = generate_nus_finalize_script(
        exp, planes="nus2d/recon.ft1", out_file="e.ft2"
    )
    assert f"| nmrPipe -fn ZF -size {plan['F1']['size']} \\" in script
    off = generate_nus_finalize_script(
        exp,
        planes="nus2d/recon.ft1",
        out_file="e.ft2",
        zero_fill={"F1": {"mode": "none"}},
    )
    assert "| nmrPipe -fn ZF" not in off

def test_3d_nus_script_phases_baked(bruker_dir: Path) -> None:
    """Complete script final run: direct dimension phase is after EXT (normalized with recon plane
    memory rotation), indirect dimension phase is filled in step3 PS, no redundant PS(0,0)
    lines."""
    exp = read_dataset(bruker_dir / "nus_3d")
    from backend.script_generator import generate_3d_nus_script

    script = generate_3d_nus_script(
        exp, in_file="e.fid", nuslist="nuslist", out_file="e.ft3",
        direct_phase=(12.0, -3.0),
        phases={"F2": (10.0, -5.0), "F1": (20.0, 3.0)},
    )
    lines = script.splitlines()
    ext_i = next(i for i, line in enumerate(lines) if "| nmrPipe -fn EXT" in line)
    step1_ps = next(
        i for i, line in enumerate(lines)
        if "| nmrPipe -fn PS -p0 12 -p1 -3 -di" in line
    )
    assert step1_ps > ext_i  # Direct dimension phase after EXT.
    assert "| nmrPipe -fn PS -p0 10 -p1 -5 -di \\" in script
    assert "| nmrPipe -fn PS -p0 20 -p1 3 -di \\" in script
    assert script.count("| nmrPipe -fn PS") == 3  # step1 + F2 + F1,No redundant 0 lines.


def test_2d_nus_script_phases_baked(bruker_dir: Path) -> None:
    exp = read_dataset(bruker_dir / "nus_2d")
    from backend.script_generator import generate_2d_nus_script

    script = generate_2d_nus_script(
        exp, in_file="e.fid", nuslist="nuslist", out_file="e.ft2",
        direct_phase=(12.0, -3.0),
        phases={"F1": (20.0, 3.0)},
    )
    lines = script.splitlines()
    ext_i = next(i for i, line in enumerate(lines) if "| nmrPipe -fn EXT" in line)
    step1_ps = next(
        i for i, line in enumerate(lines)
        if "| nmrPipe -fn PS -p0 12 -p1 -3 -di" in line
    )
    assert step1_ps > ext_i
    assert "| nmrPipe -fn PS -p0 20 -p1 3 -di \\" in script
    assert script.count("| nmrPipe -fn PS") == 2


def test_3d_nus_script_window(bruker_dir: Path) -> None:
    """NUS Window function: direct dimension (step1) and indirect dimension (step3) can be
    configured respectively, and the window is not inserted by default."""
    exp = read_dataset(bruker_dir / "nus_3d")
    from backend.script_generator import generate_3d_nus_script

    script = generate_3d_nus_script(
        exp, in_file="e.fid", nuslist="nuslist", out_file="e.ft3",
        window={
            "F3": {"type": "gaussian", "g1": 3.0, "g2": 0.2},
            "F2": {"type": "sine_bell_squared"},
            "F1": {"type": "sine_bell", "off": 0.3, "end": 0.9},
        },
    )
    # 0.2.199-patch11: direct dimension fixed SP (required by SMILE), gaussian is not used in step1.
    assert "GM" not in script
    assert "| nmrPipe -fn SP -off 0.45 -end 0.98 -pow 2 -c 0.5 \\" in script
    assert "| nmrPipe -fn SP -off 0.45 -end 0.95 -pow 2 -c 0.5 \\" in script
    assert "| nmrPipe -fn SP -off 0.3 -end 0.9 -pow 1 -c 0.5 \\" in script
    lines = script.splitlines()
    f2_sp = next(i for i, line in enumerate(lines) if "pow 2 -c 0.5" in line)
    f2_zf = next(
        i for i, line in enumerate(lines)
        if line.startswith("| nmrPipe -fn ZF") and i > f2_sp
    )
    f2_ft = next(
        i for i, line in enumerate(lines)
        if "| nmrPipe -fn FT" in line and i > f2_zf
    )
    assert f2_sp < f2_zf < f2_ft  # Window in front of ZF/FT.
    plain = generate_3d_nus_script(
        exp, in_file="e.fid", nuslist="nuslist", out_file="e.ft3"
    )
    assert "| nmrPipe -fn GM" not in plain
    assert plain.count("| nmrPipe -fn SP") == 1  # Only step1 direct dimension default window.


def test_nus_finalize_script_3d_window(bruker_dir: Path) -> None:
    exp = read_dataset(bruker_dir / "nus_3d")
    from backend.script_generator import generate_nus_finalize_script

    script = generate_nus_finalize_script(
        exp, planes="nus3d_rc/test%04d.ft1", out_file="e.ft3",
        phases={"F2": (10.0, -5.0), "F1": (20.0, 3.0)},
        window={
            "F2": {"type": "sine_bell"},
            "F1": {"type": "gaussian", "g1": 4.0},
        },
    )
    assert "| nmrPipe -fn SP -off 0.45 -end 0.95 -pow 1 -c 0.5 \\" in script
    assert "| nmrPipe -fn GM -g1 4 -g2 15 \\" in script
    lines = script.splitlines()
    sp_idx = next(i for i, line in enumerate(lines) if "pow 1 -c 0.5" in line)
    zf_idx = next(
        i for i, line in enumerate(lines)
        if "| nmrPipe -fn ZF" in line and i > sp_idx
    )
    ft_idx = next(
        i for i, line in enumerate(lines)
        if "| nmrPipe -fn FT" in line and i > zf_idx
    )
    assert sp_idx < zf_idx < ft_idx
    gm_idx = next(i for i, line in enumerate(lines) if "GM -g1 4" in line)
    zf2_idx = next(
        i for i, line in enumerate(lines)
        if "| nmrPipe -fn ZF" in line and i > gm_idx
    )
    ft2_idx = next(
        i for i, line in enumerate(lines)
        if "| nmrPipe -fn FT" in line and i > zf2_idx
    )
    assert gm_idx < zf2_idx < ft2_idx
